unicode-org/unicodetools

.github/workflows/push-jsp-on-tag.yml, UnicodeJsps/Dockerfile
whenever a new release (tag) is created, push the JSPs to gcr.io so it can be deployed.
(CLDR bug number just for tracking purposes)
=> CLDR-14145 JSP: automatically push to gcr.io on tag

UnicodeJsps/Dockerfile
It needs this same fix https://github.com/unicode-org/cldr/pull/793/files 
(more details at https://stackoverflow.com/questions/51258801/how-to-get-always-latest-link-to-download-tomcat-server-using-shell ) 
Moving to Maven would improve this as we would only depend on  the servlet API for build which doesn't change much, and then the OS provided server package.
=> JSP: fix tomcat breakage

unicodetools/data/desuffixucd.py
https://unicode-org.atlassian.net/browse/ICU-21243
=> ICU-21243 Migrates desuffixucd.py to Python 3.

unicodetools/org/unicode/text/UCD/UnicodeInvariantTest.txt
The kMandarin invariant test case failed every time kMandarin changes at all, and we have been updating the test each time to ignore any code points for which kMandarin differs from last time. Seems pointless.
Mark writes:
> That test is old. It dates from when we were constructing K Mandarin by combining to other fields. And it was a way to check that what the differences were so that we could examine them.
>
> However I think it's outlived its purpose at this point and we could remove it.
Also, the Case_Folding stability test was hardcoded to only test the characters that were new in 9.0. I changed it to test all characters that are not new now, with comments for updating it and for fixing/improving the test code.
=> remove kMandarin invariant, update Case_Folding stability

UnicodeJsps/src/main/java/org/unicode/jsp/ICUPropertyFactory.java
For #97
This is the only property-specific site that calls setUniformUnassigned that I could find so far, and it's in the JSPs.  Should there be a site within the main tools that has `NONCHARACTER_CODE_POINT` etc? 
I'll get this posted somewhere and then work on adding a test.
=> Fix Extended_Pictographic in UnicodeProperty for JSP

c/uca/sifter/unidata.txt, c/uca/sifter/unisift.c, c/uca/sifter/unisyms.c, docs/inputdata.md
From Ken:
I've now regenerated and staged unidata.txt and allkeys.txt to fix the 3
Ethiopic character names.
No change for the decomps.txt file, because those character aren't
implicated in any decompositions or other equivalences.
----
Ken also fixed a memory leak in the sifter.
And I upgraded a UCD data helper script to Python 3.
=> UCA 14 delta 13

unicodetools/data/security/14.0.0/data/confusablesSummaryIdentifier.txt, unicodetools/data/security/14.0.0/data/idnchars.txt, unicodetools/data/security/14.0.0/data/source/formatted-cherokee.txt, unicodetools/data/security/14.0.0/data/source/formatted-cjk, unicodetools/data/security/14.0.0/data/source/formatted-macFonts.txt, unicodetools/data/security/14.0.0/data/source/formatted-source.txt, unicodetools/data/security/14.0.0/data/source/formatted-winFonts.txt, unicodetools/data/security/14.0.0/data/source/removals.txt, unicodetools/data/security/14.0.0/data/xidAllowed.txt, unicodetools/org/unicode/text/UCD/MakeUnicodeFiles.txt, unicodetools/org/unicode/text/UCD/ToolUnicodePropertySource.java, unicodetools/org/unicode/text/UCD/UnicodeInvariantTest.txt
- 168-A9 Remove the assignment of GCB=SpacingMark for U+11720..11721 AHOM VOWEL SIGN A & AA, letting them default to GCB=Other
- 168-A11 Change U+17CB, U+17CC, U+17CD, U+17D0 to Identifier_Type=Recommended
=> Unicode 14 AIs 168-A9 & 168-A11

unicodetools/data/ucd/14.0.0-Update/PropList.txt, unicodetools/org/unicode/text/UCD/MakeUnicodeFiles.txt
Assign Other_Lowercase to the modifier letters in Latin Extended-F listed in L2/21-126 item β2:
10780, 10783..10785, 10787..107B0, 107B2..107B5, 107BA; and also to 107B6..107B9
Generated files in https://corp.unicode.org/~book/incoming/markus/u14/20210812/d21/
For example:
PropList.txt
```
10780         ; Other_Lowercase # Lm       MODIFIER LETTER SMALL CAPITAL AA
10783..10785  ; Other_Lowercase # Lm   [3] MODIFIER LETTER SMALL AE..MODIFIER LETTER SMALL B WITH HOOK
10787..107B0  ; Other_Lowercase # Lm  [42] MODIFIER LETTER SMALL DZ DIGRAPH..MODIFIER LETTER SMALL V WITH RIGHT HOOK
107B2..107BA  ; Other_Lowercase # Lm   [9] MODIFIER LETTER SMALL CAPITAL Y..MODIFIER LETTER SMALL S WITH CURL
```
SentenceBreakProperty.txt
```
10780         ; Lower # Lm       MODIFIER LETTER SMALL CAPITAL AA …
```
=> Unicode 14 AI 168-A2

unicodetools/org/unicode/text/UCD/GenerateBreakTest.java, unicodetools/org/unicode/text/UCD/MakeUnicodeFiles.txt, unicodetools/org/unicode/text/UCD/UCD.java, unicodetools/org/unicode/tools/SegmenterCldr.txt, unicodetools/org/unicode/tools/SegmenterDefault.txt
- remove the redundant first of three LB27 rules
- add a future-proofing LB30b rule for code points reserved for emoji (unassigned ExtPict)
=> Unicode 14 line break rule changes

docs/index.md
Fixes #133 
I tried to refactor the instructions into shared setup + CLI-specific/Eclipse-specific.  
We should verify and expand the list of the common tasks that are invoked from unicodetools.  (And then make sure that they are reflected somewhere in the Github Actions CI jobs.)
=> Update docs for setup of Maven + {CLI,Eclipse}

docs/help/bidi.md, docs/help/breaks.md, docs/help/changes.md, docs/help/character.md, docs/help/index.md, docs/help/list-unicodeset.md, docs/help/properties.md
Fixes #138 
This is based on top of @macchiati 's PR #141 to land the initial auto-converted Markdown files of the original help site pages.
I configured my personal to serve pages out of this PR's branch from the `/docs` directory, so https://echeran.github.io/unicodetools/help should be a preview.  Reminder: https://cldr.unicode.org/unicode-utilities/ is the original site we're migrating from.
=> Fix Markdown formatting in the help pages for the JSPs

docs/build.md, unicodetools/src/main/java/org/unicode/text/UCD/CompareProperties.java, unicodetools/src/main/java/org/unicode/text/UCD/GenerateBreakTest.java, unicodetools/src/main/java/org/unicode/text/UCD/GenerateCaseFolding.java, unicodetools/src/main/java/org/unicode/text/UCD/GenerateData.java, unicodetools/src/main/java/org/unicode/text/UCD/GenerateNamedSequences.java, unicodetools/src/main/java/org/unicode/text/UCD/GenerateStandardizedVariants.java, unicodetools/src/main/java/org/unicode/text/UCD/MakeUnicodeFiles.java, unicodetools/src/main/java/org/unicode/text/utility/Settings.java, unicodetools/src/main/java/org/unicode/text/utility/UnicodeDataFile.java, unicodetools/src/main/resources/org/unicode/text/UCD/MakeUnicodeFiles.txt
Now that we no longer generate files with versioned suffixes,
- delete the `DeltaVersion` line in MakeUnicodeFiles.txt
- remove the `dVersion` field in MakeUnicodeFiles.java
- write UCD output files into Generated/UCD/15.0.0 instead of Generated/UCD/d24
- simplify UnicodeDataFile.FileInfix and its call sites
Fixes issue #161
=> remove MakeUnicodeFiles.DeltaVersion

pom.xml, unicodetools/src/main/java/org/unicode/text/tools/CLDRCharacterUtility.java
- per CLDR-15195
- Now updates to CLDR version 0.0.0-SNAPSHOT-472af8d773
- CLDR release: snapshot/2022-01-10
- https://github.com/unicode-org/cldr/releases/tag/snapshot%2F2022-01-10
=> Update to CLDR version that includes jar sources

unicodetools/data/ucd/dev/DerivedNormalizationProps.txt, unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
The new Egyptian format controls are not default ignorable.
Fix derived NFKC_CF data for them, and adjust an invariant test case.
These fixes should have been part of PR #203 but I had tooling problems last week :-/
=> fixes for new Egyptian controls not default ignorable

.github/workflows/pythonpackage.yml, py/tabcheck.py
- add a simple Python script that checks all .java files in the project for tab characters. The script prints the full path of each file found containing tabs and fails if any are found. The script can be run independently of CI.
- minor modifications to the Python workflow to link up the tab check script
=> Add tab check

UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeProperty.java, UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeSetUtilities.java, unicodetools/src/main/java/org/unicode/jsp/ICUPropertyFactory.java, unicodetools/src/main/java/org/unicode/jsp/MySymbolTable.java, unicodetools/src/main/java/org/unicode/props/UnicodeProperty.java, unicodetools/src/main/java/org/unicode/props/UnicodePropertySymbolTable.java, unicodetools/src/main/java/org/unicode/text/UCD/GenerateConfusables.java, unicodetools/src/main/java/org/unicode/text/UCD/GenerateConfusablesCopy.java, unicodetools/src/main/java/org/unicode/text/UCD/TestData.java, unicodetools/src/main/java/org/unicode/text/UCD/TestUnicodeInvariants.java
and then clean up most warnings in UnicodeProperty
For issue #66: This makes unicodetools UnicodeProperty more like CLDR UnicodeProperty. The CLDR version switched to Java Predicate in https://github.com/unicode-org/cldr/pull/460. The warnings cleanup here goes farther than the earlier one in CLDR.
Best to review one commit at a time.
=> switch from ICU ObjectMatcher to Java Predicate

UnicodeJsps/.settings/org.eclipse.core.resources.prefs, UnicodeJsps/.settings/org.eclipse.wst.common.component, UnicodeJsps/.settings/org.eclipse.wst.common.project.facet.core.xml, UnicodeJsps/pom.xml, pom.xml, unicodetools-testutils/.settings/org.eclipse.core.resources.prefs, unicodetools-testutils/.settings/org.eclipse.jdt.core.prefs, unicodetools-testutils/.settings/org.eclipse.m2e.core.prefs, unicodetools-testutils/pom.xml, unicodetools/.project, unicodetools/.settings/org.eclipse.jdt.core.prefs, unicodetools/.settings/org.eclipse.wst.common.component, unicodetools/.settings/org.eclipse.wst.common.project.facet.core.xml, unicodetools/.settings/org.eclipse.wst.validation.prefs, unicodetools/pom.xml
For: #218
Followon to: #224
- to pickup JDK11 fixes
- Also, dropped some unneeded lines from pom.xml (duplicate version and groupId fields) to fix warnings
- This is CLDR `0.0.0-SNAPSHOT-e849e51d51` corresponding to [`snapshot/2022-04-25`](https://github.com/unicode-org/cldr/releases/tag/snapshot%2F2022-04-25)
- Also checkin some .settings files that eclipse seems to want to modify
=> deps: use prerelease CLDR 42 dev tag

unicodetools/data/ucd/dev/auxiliary/GraphemeBreakProperty.txt, unicodetools/src/main/java/org/unicode/text/UCD/ToolUnicodePropertySource.java
= partial reverse of pull request #181
Fixes UTC action item [171-A69](https://www.unicode.org/cgi-bin/GetL2Ref.pl?171-A69).
After bug reports, and discussion in UTC 171, it was decided for Kawi line breaking to follow Western style for now, and try to default to orthographic syllables in the future, rather than using East Asian style (with the whole script in lb=SA).
=> include Kawi postbase (gc=Mc, InPC=Right) characters in GCB=SpacingMark

unicodetools/data/security/dev/IdentifierStatus.txt, unicodetools/data/security/dev/IdentifierType.txt, unicodetools/data/security/dev/confusables.txt, unicodetools/data/security/dev/confusablesSummary.txt, unicodetools/data/security/dev/data/draft-restrictions.txt, unicodetools/data/security/dev/data/idnchars.txt, unicodetools/data/security/dev/data/source/removals.txt, unicodetools/src/main/java/org/unicode/text/UCD/GenerateConfusablesCopy.java, unicodetools/src/main/java/org/unicode/text/UCD/IdentifierInfo.java, unicodetools/src/test/java/org/unicode/propstest/TestInvariants.java
For
[[171-A128](https://www.unicode.org/cgi-bin/GetL2Ref.pl?171-A128)] Action Item for Mark Davis: In the property files IdentifierStatus.txt and IdentifierType.txt, remove the Joiner_Control characters ZWJ and ZWNJ from Identifier_Type=Inclusion and Identifier_Status=Allowed. For Unicode version 15.0.
removals.txt has overrides for ZWJ & ZWNJ, setting them to Identifier_Type=Inclusion.
By removing them, they default to Identifier_Type=Default_Ignorable.
All data files other than removals.txt are modified by the tool.
There are also changes for U+13440 EGYPTIAN HIEROGLYPH MIRROR HORIZONTALLY (still Exclusion but no longer Not_XID). I assume that they are due to changes in other properties.
The confusables changes are only in comments. I think I have seen some of these flip-flopping but …
=> ZWJ/ZWNJ not Identifier_Status=Allowed

c/uca/sifter/cttfooter.txt, c/uca/sifter/unisift.c, c/uca/sifter/unisyms.c
From Ken:
The only changes for 15.0 are:
unisift.c
A bunch of version and date updates;
updates for CJK ranges;
http: --> https: updates in a couple outputs for terms of use;
tweaks to the kana mapping tables for the two new small kana characters.
unisyms.c
Updates to the symbol tables for 5 new combining marks
(and for removing the explicit separate weight for the Phaistos Disc symbol mark);
updates of SMP block ranges to make sure all the appropriate
ranges of symbolic weights get output correctly.
cttfooter.txt
Updates for some CJK ranges in the static text appended at the bottom of
the CTT table output.
=> UCA 15 sifter code changes

c/uca/sifter/build.sh
Just a documentation update. The sifter builds fine against ICU and outputs the same allkeys.txt as the one in this repo.
=> update sifter QA command lines

unicodetools/data/ucd/dev/extracted/DerivedEastAsianWidth.txt, unicodetools/data/ucd/dev/extracted/DerivedLineBreak.txt, unicodetools/src/main/java/org/unicode/props/DefaultValues.java, unicodetools/src/main/java/org/unicode/text/UCD/MakeUnicodeFiles.java, unicodetools/src/main/java/org/unicode/tools/emoji/GenerateEmojiData.java
For UTC action item [168-A7](https://www.unicode.org/cgi-bin/GetL2Ref.pl?168-A7): Propose a change in one or more UCD files to use multiple `@missing` lines; for Unicode version 15.0. See document L2/21-126 item D2.
PR #267 did this for Bidi_Class.
This PR now does the same thing for East_Asian_Width & Line_Break.
Writing multiple `@missing` lines for Extended_Pictographic is incomplete, mostly because the UCD syntax does not yet support it. I added most of the necessary code and left comments about the status.
See also
- https://www.unicode.org/reports/tr44/#Complex_Default_Values
- https://www.unicode.org/reports/tr44/#Missing_Conventions
=> write multiple ea/lb @missing lines

unicodetools/data/emoji/dev/emoji-data.txt, unicodetools/data/ucd/dev/emoji/emoji-data.txt, unicodetools/src/main/java/org/unicode/tools/emoji/GenerateEmojiData.java
Fixes [172-A73](https://www.unicode.org/L2/L2022/22121.htm) “Action Item for Ned Holbrook, Markus Scherer, PAG: In emoji-data.txt, remove the `@missing` lines; for Unicode Version 15.0.”
=> Remove @missing lines from emoji-data.txt

unicodetools/data/ucd/dev/PropertyValueAliases.txt, unicodetools/src/main/java/org/unicode/props/PropertyParsingInfo.java, unicodetools/src/main/java/org/unicode/text/UCD/MakeUnicodeFiles.java
[172-A71] Action Item for Markus Scherer, PAG: In PropertyValueAliases.txt remove the `@missing` lines for Equivalent_Unified_Ideograph, Bidi_Mirroring_Glyph and NFKC_Casefold and Script_Extensions; for Unicode Version 15.0.
Modified Java generator code and generated output.
The IndexUnicodeProperties / PropertyParsingInfo code seems to use the latest Unicode version's PVA.txt `@missing` values when parsing old data files, such as Unicode 6.0 ScriptExtensions.txt which did not have an `@missing` line. I modified the parser to set the default values for the properties above when there is no `@missing` line in the specific data file. (FYI @macchiati)
=> PVA: remove redundant at-missing lines

unicodetools/data/uca/dev/CollationTest.html
Note: Use the CLDR versions of the UCA conformance test files for implementations using CLDR/ICU.
=> CLDR test files for impls using CLDR/ICU

unicodetools/data/ucd/dev/StandardizedVariants.txt
From Ken: I just took care of an issue Charlotte Buff noted, where incomplete names were given for 4 Egyptian lost signs in their entries in StandardizedVariants.txt. These names are in comments, and don't affect any normative content or any derivations here, so nothing else will be impacted.
=> StandardizedVariants: fix some names in comments

pom.xml, unicodetools/data/security/dev/IdentifierStatus.txt, unicodetools/data/security/dev/IdentifierType.txt, unicodetools/data/security/dev/confusables.txt, unicodetools/data/security/dev/data/draft-restrictions.txt, unicodetools/data/security/dev/data/idnchars.txt, unicodetools/data/security/dev/data/source/removals.txt, unicodetools/src/main/java/org/unicode/text/UCD/IdentifierInfo.java, unicodetools/src/test/java/org/unicode/propstest/TestInvariants.java
Change .../security/dev/data/source/removals.txt to do
- [172-A61] Action Item for Mark Davis, PAG: Change the Identifier_Type of U+A7AE to Technical (and thus its Identifier_Status to Restricted), for Unicode Version 15.0. See L2/22-124 item UCD7.
- [172-A62] Action Item for Mark Davis, PAG: Change the Identifier_Type of U+A7B8 and U+A7B9 to Uncommon_Use (and thus their Identifier_Status to Restricted), for Unicode Version 15.0. See L2/22-124 item UCD8.
Then generate the other security data files and adjust the TestInvariants unit test.
In addition, do the generator code + data file parts of
- [169-A1] In IdentifierStatus.txt and IdentifierType.txt, replace comments with appropriate `@missing` lines. See L2/21-170 item F1. Reference UAX `#44` in the format for data files and spec for UTS …
=> Unicode 15 security data final AIs

.github/workflows/cli-build-instructions.yml, docs/build.md, unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
- Updated UnicodeInvariantTest.txt (Misc. section) with check for non-Alphabetic InSc=Bindus. See #289.
- Added step to cli-build-instructions.yml workflow to upload generated `UnicodeTestResults.html` file as a build artifact (out-of-source build). This step is set to run `always()` so it will attempt to upload the artifact even if previous steps fail.
=> Add test for non-alphabetic InSC=Bindu

unicodetools/src/main/java/org/unicode/text/UCD/GenerateCaseFolding.java, unicodetools/src/main/java/org/unicode/text/UCD/UCD.java
For
- [171-A122] ... Check the case chart generator for how U+0130 is processed, and fix if necessary
The case mapping code in Java class UCD had a bug for the full lowercase mapping of U+0130 LATIN CAPITAL LETTER I WITH DOT ABOVE. This was visible in the Latin-script case chart.
See SpecialCasing.txt:
```
0130; 0069 0307; 0130; 0130; # LATIN CAPITAL LETTER I WITH DOT ABOVE
...
0130; 0069; 0130; 0130; tr; # LATIN CAPITAL LETTER I WITH DOT ABOVE
0130; 0069; 0130; 0130; az; # LATIN CAPITAL LETTER I WITH DOT ABOVE
```
I then had to more strongly hardcode the case folding of variants of i to keep those mappings stable.
=> fix the U+0130 full lowercase mapping

unicodetools/data/security/dev/IdentifierStatus.txt, unicodetools/data/security/dev/IdentifierType.txt, unicodetools/data/security/dev/confusables.txt, unicodetools/data/security/dev/confusablesSummary.txt, unicodetools/data/security/dev/data/confusablesSummaryIdentifier.txt, unicodetools/data/security/dev/data/idnchars.txt, unicodetools/data/security/dev/data/source/formatted-cherokee.txt, unicodetools/data/security/dev/data/source/formatted-cjk, unicodetools/data/security/dev/data/source/formatted-macFonts.txt, unicodetools/data/security/dev/data/source/formatted-source.txt, unicodetools/data/security/dev/data/source/formatted-winFonts.txt, unicodetools/data/security/dev/data/xidAllowed.txt, unicodetools/data/security/dev/intentional.txt, unicodetools/src/main/java/org/unicode/text/UCD/GenerateConfusables.java
The file-initial Byte Order Mark is not recommended for UTF-8 (where it is more properly a ["signature byte sequence"](https://www.unicode.org/reports/tr6/tr6-4.html#Signature)). Stop writing it for security data files.
Fixes #123
=> security data files without UTF-8 BOM

.flake8, .github/workflows/build-jsp.yml, .github/workflows/cli-build-instructions.yml, .github/workflows/push-jsp-on-tag.yml, .github/workflows/pythonpackage.yml, unicodetools-testutils/src/test/java/org/unicode/unittest/TestTestFmwk.java
- github action should use the cldr.version for checkout
- also bump the version of some actions
Fixes #316
=> fix(build): use cldr.version for cldr

.gitignore, UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeJsp.java, UnicodeJsps/src/main/webapp/character.jsp, docs/unicodejsps/index.md, unicodetools/.project
As well as a number of other hex escape and hex numeric literal syntaxes.
This fixes #350.
Provide some help in an error message if we still get multiple code points, pointing to the pages for the individual code points, which can be useful when one is interested in combining marks; see screenshots below.
Drive-by changes to documentation so that it doesn’t suggest a running maven in a place where it doesn’t see the POM, and to .gitignore so that it ignores the Generated directory suggested by the build instructions.
Unfortunately this breaks this important feature of character.jsp: https://util.unicode.org/UnicodeJsps/character.jsp?a=%F0%9F%90%88%22/%3E%3Cscript%3Ealert(%22meow%22)%3C/script%3E%3Cspan%20class=%22&B1=Show.
Screenshots:
| U+ notation | Multiple code points | Escaping | …
=> Support U+ notation in character.jsp

unicodetools/data/ucd/dev/NamesList.txt
From Ken:
[[174-A55](https://www.google.com/url?q=https://www.unicode.org/cgi-bin/GetL2Ref.pl?174-A55)] Action Item for Ken Whistler, EDC: Add the annotations for the 115 characters in the CJK Radicals Supplement block to the UCD’s NamesList.txt data file, based on document [L2/22-287](https://www.google.com/url?q=https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/22-287) and Section 15 of document [L2/23-011](https://www.google.com/url?q=https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/23-011) and its attached NamesList-20230106.txt data file, for Unicode Version 15.1.
=> add annotations for the CJK Radicals Supplement block

docs/data-workflow.md, pub/copy-alpha-to-draft.sh
Shell script which copies the alpha review files (UCD & emoji) from a local git clone of the unicodetools repo to the folder behind https://www.unicode.org/Public/draft/ (or to a staging area for that).
=> script: copy alpha files to draft

docs/data-workflow.md, pub/copy-alpha-to-draft.sh
@nedley de-duplicated two emoji files in PR #397 so the copy-alpha script need not delete those any more.
Workflow: Don't assume that the script is run on the unicode.org server; send Rick a zip file with the contents of the “draft” target folder.
=> alpha data workflow update: emoji files deduped, zip draft folder

.github/workflows/push-jsp-on-tag.yml, UnicodeJsps/.gitignore
#271
understandably, they've removed v1.2 as a tag. But the SHA is still there
We need this version because we need the functionality to checkout a short hash (from the CLDR pom version)
=> fix(build): jsp: fix checkout for push to GCR

.gitattributes, .mvn/jvm.config
Workaround taken from https://github.com/diffplug/spotless/issues/834#issuecomment-817524058.
See also https://github.com/google/google-java-format/issues/538.
=> Work around spotless issues in recent JDKs

.github/workflows/cache_retain.yml
Fixes #421 
This is basically a copy of the [ICU CI workflow](https://github.com/unicode-org/icu/blob/main/.github/workflows/cache_retain.yml) that does the same. Except that instead of doing _something_, I think doing _nothing_ is sufficient because the Github's cache action only cares about the job success status.
cc @eggrobin
=> Add CI workflow to prevent Maven cache from getting evicted

unicodetools/src/main/java/org/unicode/text/UCD/ScriptExtensions.java
Regenerating the UCD currently flips `# Script_Extensions=Arab Nkoo` and `# Script_Extensions=Arab Rohg`, as was noted by @markusicu in https://github.com/unicode-org/unicodetools/pull/416#issuecomment-1456708673. This is very annoying in the new world where we want to have many draft PRs in flight for a long time, requiring frequent regeneration of the UCD.
This is happening because #398 ordered these inconsistently with the order produced by `MakeUnicodeFiles`. That was intentional: the pull request description reads
> Sort scripts, first by count, and then alphabetically
This was already the case, but the sorting was alphabetical by alias, rather than script code, and `Rohg`=`Hanifi_Rohingya`<`Nko`=`Nkoo`. The alternative to this PR would be for @roozbehp to change the logic in …
=> Sort scx based on script codes rather than aliases.

unicodetools/data/ucd/dev/EastAsianWidth.txt, unicodetools/data/ucd/dev/LineBreak.txt, unicodetools/data/ucd/dev/VerticalOrientation.txt, unicodetools/src/main/java/org/unicode/text/UCD/MakeUnicodeFiles.java, unicodetools/src/main/java/org/unicode/text/UCD/ToolUnicodePropertySource.java, unicodetools/src/main/resources/org/unicode/text/UCD/MakeUnicodeFiles.txt
Follow-up on #438: MakeUnicodeFiles now does the three Ken files.
Correct an obsolete comment in LB and EAW.
Also fix the VerticalOrientation property created by ToolUnicodePropertySource, which caused UnicodeSet to be wrong about sets based on VO: compare
https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3ACn%3A%5D%26%5B%3Ablk%3DTangut%3A%5D%26%5B%3AVO%3DU%3A%5D&g=&i=
and 
https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3ACn%3A%5D%26%5B%3Ablk%3DTangut%3A%5D&g=VO
=> Regenerate EAW and VO, fix a UnicodeSet bug

unicodetools/src/main/java/org/unicode/text/UCD/MakeUnicodeFiles.java, unicodetools/src/main/java/org/unicode/text/UCD/UCD_Names.java, unicodetools/src/main/java/org/unicode/text/UCD/UCD_Types.java
Eventually we should get rid of UCD_Names and UCD_Types, but in the meantime MakeUnicodeFiles depends on them.
While we might hope to make merging of data files painless with #419, this is not going to happen for Java, and since these files are not generated, we should avoid having to resolve merge conflicts there.
At the same time, since the plan is to do the propertizing ahead of the ISO 15924 registration, we need to make sure the private use codes for the pipeline do not collide.
Thus this PR propels UCD_Names and UCD_Types into the distant future, while ensuring that the future scripts do not show up in the generated files. Note that GenerateEnums will not pick those up, since that is based on PVA from which they are suppressed in MakeUnicodeFiles.
=> Scripts from the future

unicodetools/data/ucd/dev/NamesList.txt
From Ken:
I've made a small update to NamesList.txt. ...
The only change is to activate the printing of the standardized
variation sequences summary chart for the Egyptian hieroglyphs, now that
Michel has the font support for them.
=> NamesList from Ken 2023feb20

unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
There is one exception, we should avoid adding more.
See discussion in https://github.com/unicode-org/unicode-reports/pull/67#discussion_r1163796866.
(Expected) test failure at e677c9a8ffa9b48d1cfa8488216d17b6782fa7c8:
```
[\p{ID_Start}] ⊇ $identifier_start
**** START Test Failure 1 ****
2E2F	#		(ⸯ)	VERTICAL TILDE
**** END Test Failure 1 ****
[\p{ID_Continue}] ⊇ [$identifier_start $identifier_extend]
**** START Test Failure 2 ****
2E2F	#		(ⸯ)	VERTICAL TILDE
**** END Test Failure 2 ****
[\p{XID_Start}] ⊇ [$identifier_start-\p{NFKC_QC=No}]
**** START Test Failure 3 ****
2E2F	#		(ⸯ)	VERTICAL TILDE
**** END Test Failure 3 ****
[\p{XID_Continue}] ⊇ [[$identifier_start $identifier_extend]-\p{NFKC_QC=No}]
**** START Test Failure 4 ****
2E2F	#		(ⸯ)	VERTICAL TILDE
**** END Test Failure 4 ****
```
=> Add an invariant test for compatibility with Unicode 3 identifier definitions

unicodetools/src/test/java/org/unicode/propstest/TestProperties.java
Fix #437.
With this test, #435 fails with the following error:
```
[ERROR] Tests run: 10, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 2.19 s <<< FAILURE! - in org.unicode.propstest.TestProperties
[ERROR] org.unicode.propstest.TestProperties.TestJoiningGroupConsistency  Time elapsed: 0.03 s  <<< FAILURE!
org.opentest4j.AssertionFailedError:
U+062F (د) ARABIC LETTER DAL
and
U+10EC2 (𐻂) ARABIC LETTER DAL WITH TWO DOTS VERTICALLY BELOW
have different joining types but are in the same joining group (Dal)
==> expected: <Right_Joining> but was: <Dual_Joining>
at org.unicode.propstest.TestProperties.lambda$1(TestProperties.java:229)
at org.unicode.propstest.TestProperties.lambda$0(TestProperties.java:227)
at org.unicode.propstest.TestProperties.TestJoiningGroupConsistency(TestProperties.java …
```
=> Test that Joining_Group refines Joining_Type

unicodetools/src/main/java/org/unicode/tools/emoji/ChartUtilities.java, unicodetools/src/main/java/org/unicode/tools/emoji/CountEmoji.java, unicodetools/src/main/java/org/unicode/tools/emoji/EmojiData.java, unicodetools/src/main/java/org/unicode/tools/emoji/ProposalData.java
While reviewing charts I discovered a longstanding issue with the one for proposals “by emoji”: it was omitting all sequences containing U+FE0F due to an overzealous skeleton comparison. For example, if you look at https://www.unicode.org/emoji/charts-15.0/emoji-proposals.html the proposal for heart on fire is listed but that is the only reference to that proposal on the page, plus the pilot sequences are missing (among others).
This also applies the fix for #95 to the proposals chart.
=> Fix proposals for sequences containing U+FE0F

unicodetools/data/ucd/dev/PropList.txt, unicodetools/data/ucd/dev/auxiliary/SentenceBreakProperty.txt
UTC-175-A75: Add U+17D4 KHMER SIGN KHAN & U+17D5 KHMER SIGN BARIYOOSAN to Sentence_Terminal and Sentence_Break=STerm, for Unicode 15.1.
=> Add 2 Khmer characters to Sentence_Terminal

unicodetools/data/ucd/dev/NamesList.html
From Ken:
This updated a bullet that explains the lookbehind logic for
intercepting various standards identifiers and preventing four digit
identifiers for them (e.g. ISO 6429) from turning into Unicode
characters in the output line. Asmus has added detection of IEEE, KSC X,
and GB to the list that is supported for this special processing.
=> NamesList.html from Ken may09

unicodetools/data/ucd/dev/NamesList.txt
Ken via file header:
Tweak use of notices to suppress year expansions.
Update annotations for 06F4..06F7.
Ken via email:
This delta fixes some annotations for Eastern Arabic digits, and also
removes some unnecessary notice prefixes on annotation lines that
contain numbers for standards (like "ISO 2047", etc.)
=> NamesList.txt 15.1 may12

UnicodeJsps/src/test/java/org/unicode/jsptest/TestJsp.java, unicodetools/data/idna/dev/IdnaMappingTable.txt, unicodetools/data/idna/dev/IdnaTestV2.txt, unicodetools/src/main/java/org/unicode/idna/GenerateIdna.java, unicodetools/src/test/java/org/unicode/propstest/TestInvariants.java, unicodetools/src/test/java/org/unicode/unittest/TestIdnaTest.java
For
[[175-A86](https://www.unicode.org/cgi-bin/GetL2Ref.pl?175-A86)] Action Item for Mark Davis, Markus Scherer, PAG: In IdnaMappingTable.txt, change U+2260 (≠), U+226E (≮), and U+226F (≯) from disallowed_STD3_valid to valid, for Unicode 15.1.
In the code for [Mapping Table Derivation, Step 7](https://unicode.org/reports/tr46/#TableDerivationStep7), we no longer check whether the NFD versions of characters and mappings are valid. We had agreed with feedback that that is not necessary because domain names are in composed form, not decomposed.
----
Also adds the other characters that are new in Unicode 15.1:
- 5 new IDS characters
- 603 new characters in CJK Extension I
=> IDNA 15.1: new CJK; no NFD validity check

unicodetools/data/ucd/dev/DerivedCoreProperties.txt, unicodetools/src/main/resources/org/unicode/text/UCD/MakeUnicodeFiles.txt
[[174-A5](https://www.unicode.org/cgi-bin/GetL2Ref.pl?174-A5)] Action Item for Ken Whistler, PAG: In DerivedCoreProperties.txt, document the implications of changing Default_Ignorable_Code_Point, for Unicode Version 15.1. See document [L2/23-008](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/23-008) item 1.1.
=> Text from Ken for 174-A5

UnicodeJsps/src/main/java/org/unicode/jsp/CachedProps.java, UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeJsp.java
Per discussion in unicodetools meeting 13 June 2023:
- "The beta version string should just use Settings.latestVersion" — updated UnicodeJsp.java to use Settings.latestVersion
- "The jspVersionInfo should use UCharacter.getUnicodeVersion() to match what it serves — as long as it serves ICU property values" — reworked CachedProps.java to use UCharacter.getInstance for jspVersionInfo
=> Fix Jsp versioning

unicodetools/data/idna/dev/IdnaMappingTable.txt, unicodetools/data/idna/dev/IdnaTestV2.txt, unicodetools/src/main/java/org/unicode/idna/GenerateIdna.java, unicodetools/src/main/java/org/unicode/idna/GenerateIdnaTest.java, unicodetools/src/test/java/org/unicode/unittest/TestIdnaTest.java
Changes for new action items from UTC-176:
- In UTS46 Mapping Table Derivation step 1 (base mapping) substep 1 (exceptional characters), map U+1E9E capital sharp s to U+00DF small sharp s. Add a note that this changes the mapping of the capital sharp s. For Unicode 15.1.
- In IdnaMappingTable.txt map U+1E9E capital sharp s to U+00DF small sharp s instead of to "ss", for Unicode 15.1.
*Please read the following and advise!*
It turns out that the first action item (adding a base  mapping) is insufficient: Table derivation step 6 checks that the mapping contains only characters in the base valid set before using the mapping. Lowercase sharp s is not in the base valid set (it has an NFKC_Casefold mapping). Thus, the mapping table is generated with capital sharp s disallowed.
I chose to add …
=> UTS46 map capital to lowercase sharp s

unicodetools/data/idna/dev/IdnaMappingTable.txt, unicodetools/data/idna/dev/IdnaTestV2.txt, unicodetools/src/main/java/org/unicode/idna/GenerateIdna.java
which overflowed from the now-filled Ideographic_Description_Characters block
also picks up new end of CJK extension I
FYI @michelsu
=> UTS46 disallow new IDC U+31EF

unicodetools/data/idna/dev/IdnaTestV2.txt, unicodetools/src/main/java/org/unicode/idna/Uts46.java
... to keep the mapping idempotent, and to avoid the small sharp s failing the mode=transitional validity check
FYI @michelsu
=> UTS46 transitional: map capital sharp s to ss

unicodetools/data/ucdxml/dev/ucdxml.readme.txt
@liancu-uni provided the UCDXML versions of what should be the final Unicode 15.1 data.
I ran the CheckXmlProperties program. The "failures" that it prints all look like the known value representation issues as before (see issue #325).
=> UCDXML 15.1 2023aug16

unicodetools/data/uca/dev/CollationTest.html
@Ken-Whistler said in a meeting that it's ok to delete these very old notes now.
=> CollationTest.html: remove very old Migration notes

docs/data-workflow.md
I realized that `<version>` strings don't render, presumably because they are interpreted as (undefined) HTML tags.
Compare
- https://github.com/unicode-org/unicodetools/blob/main/docs/data-workflow.md#publish-a-release
- https://github.com/markusicu/unicodetools/blob/workflow-md-dont-hide-versions/docs/data-workflow.md#publish-a-release
=> change version placeholders so .md shows them

UnicodeJsps/src/main/java/org/unicode/jsp/CachedProps.java, UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeUtilities.java
Someday we could try being smarter and classify the name aliases by type, excluding figment, alternate, and abbreviation to cut down on the noise, and showing the correction ones even alongside the name. But until that day, this fixes #542.
[And we’re out of β, we’re releasing on time…](https://www.youtube.com/watch?v=Y6ljFaKRTrI)
=> Show the Name_Alias in the absence of a name in the jsps

unicodetools/src/main/java/org/unicode/text/UCD/TestUnicodeInvariants.java, unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
Test what we actually want to test, instead of having to pile on more inscrutable exceptions whenever we add decompositions.
=> Make the canonical decomposition invariant test easier to maintain

unicodetools/data/ucd/dev/IndicPositionalCategory.txt, unicodetools/data/ucd/dev/IndicSyllabicCategory.txt, unicodetools/src/main/java/org/unicode/text/UCD/MakeUnicodeFiles.java, unicodetools/src/main/resources/org/unicode/text/UCD/MakeUnicodeFiles.txt
Follow-up on #438, #448, and #449; see rationale in #438.
=> Make MakeUnicodeFiles regenerate IndicMeowCategory.txt

unicodetools/src/main/java/org/unicode/props/UcdLineParser.java
I think this fixes #419, at last.
=> Ignore conflict markers in UcdLineParser

unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
There are a handful of exceptions*, but most of them are alphabetic. See TUS on Alphabetic:
> **_Alphabetic._** The Alphabetic property is a derived informative property of the primary units of alphabets and/or syllabaries, whether combining or noncombining. Included in this group would be composite characters that are canonical equivalents to a combining character sequence of an alphabetic base character plus one or more combining characters; letter digraphs; contextual variants of alphabetic characters; ligatures of alphabetic characters; contextual variants of ligatures; modifier letters; letterlike symbols that are compatibility equivalents of single alphabetic letters; and miscellaneous letter elements. Notably, U+00AA feminine ordinal indicator and U+00BA masculine ordinal indicator …
=> Add an invariant relating Vowel_Dependent to Alphabetic

unicodetools/src/main/java/org/unicode/text/UCA/ReorderCodes.java
Add draft script sample characters (from the draft CLDR script metadata) for Unicode 16+ scripts.
Removes one hurdle for running UCA.Main for Unicode 16+.
UCA.Main still fails for lack of allkeys data for new characters.
=> UCA: new-script draft sample characters for 16+

unicodetools/src/main/java/org/unicode/text/UCD/MakeUnicodeFiles.java
Cherry-picked from https://github.com/unicode-org/unicodetools/pull/580.
These could lead to derived files inconsistent with the source files if we forgot to update the hardcoded DefaultValues.java.
=> Remove scary assumptions

unicodetools/src/main/java/org/unicode/jsp/FileUtilities.java
It just so happens that #419 is only _mostly_ fixed.
=> Ignore conflict markers in ScriptExtensions

unicodetools/data/ucd/dev/IndicPositionalCategory.txt, unicodetools/src/main/resources/org/unicode/text/UCD/MakeUnicodeFiles.txt, unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
It turns out we want it, see https://github.com/unicode-org/unicodetools/pull/445#issuecomment-1798359742.
This is consistent with Roozbeh’s file.
I will fix the linewrapping of the header later, in the Gurung Khema PR.
=> Indic_Positional_Category for Kirat Rai

unicodetools/data/ucd/dev/IndicPositionalCategory.txt, unicodetools/src/main/resources/org/unicode/text/UCD/MakeUnicodeFiles.txt
Part of [177-A94](https://www.unicode.org/cgi-bin/GetL2Ref.pl?177-A94). The data had already been changed, but the header remained intact. It needed to change to reflect the data change.
[[177-C41](https://www.unicode.org/cgi-bin/GetL2Ref.pl?177-C41)] Consensus: Change the InPC property value for U+0D41 MALAYALAM VOWEL SIGN U and U+0D42 MALAYALAM VOWEL SIGN UU from Right to Bottom for Unicode version 16.0. (Ref. [L2/23-200](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/23-200))
[[177-A94](https://www.unicode.org/cgi-bin/GetL2Ref.pl?177-A94)] Action Item for Roozbeh Pournader, SAH: Update the IndicPositionalCategory.txt and add comments based on document [L2/23-238](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/23-238) and discussion in the Script Ad Hoc for Unicode version …
=> Move and expand comment on Malayalam U and UU

unicodetools/data/ucd/dev/IndicSyllabicCategory.txt, unicodetools/data/ucd/dev/PropertyValueAliases.txt, unicodetools/src/main/java/org/unicode/props/UcdPropertyValues.java, unicodetools/src/main/resources/org/unicode/text/UCD/MakeUnicodeFiles.txt, unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
[[177-C42](https://www.unicode.org/cgi-bin/GetL2Ref.pl?177-C42)] Consensus: Add a new property value Reordering_Killer to IndicSyllabicCategory.txt for Unicode version 16.0. (Ref. [L2/23-205](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/23-205) and Section 18 of [L2/23-238](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/23-238))
[[177-C43](https://www.unicode.org/cgi-bin/GetL2Ref.pl?177-C43)] Consensus: Change the InSC property values for the Batak viramas U+1BF2 BATAK PANGOLAT and U+1BF3 BATAK PANONGONAN from Pure_Killer to Reordering_Killer for Unicode version 16.0. (Ref. [L2/23-205](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/23-205) and Section 18 of [L2/23-238](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/23-238)) …
=> Add new InSC property value Reordering_Killer and move Batak viramas to it

UnicodeJsps/src/main/java/org/unicode/jsp/XPropertyFactory.java, UnicodeJsps/src/test/java/org/unicode/jsptest/TestMultivalued.java, UnicodeJsps/src/test/java/org/unicode/jsptest/TestScriptExtensions.java, UnicodeJsps/src/test/java/org/unicode/jsptest/TestUnicodeSet.java, unicodetools/src/main/java/org/unicode/props/UnicodeProperty.java
Fixes https://github.com/unicode-org/unicodetools/issues/192
scx=deva has not been working; the results were essentially the same as sc=deva
As it turns out, the code really never accounted for multivalued properties. So when testing for values, an scx value like "Devanagari,Bengali" would be skipped. 
The code change was simple; to change the code so that a UnicodeProperty could be marked as multivalued, and when comparing values there would be an extra level: splitting the property value if there was a ",", and otherwise testing like a single value. Now, this is done on each unique value rather than on each code point, so it doesn't affect performance much (especially as there are not many unique multivalue property values).
Ideally we should revamp UnicodeProperty to support …
=> Fix JSP failures with scx

UnicodeJsps/src/main/java/org/unicode/jsp/ScriptTester.java, UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeSetUtilities.java, UnicodeJsps/src/main/java/org/unicode/jsp/XPropertyFactory.java, UnicodeJsps/src/test/java/org/unicode/jsptest/TestMultivalued.java, unicodetools/src/main/java/org/unicode/props/UnicodeProperty.java
There were two further problems with multivalued support
1. \p{exemplar} (has no exemplar value) returned the reverse of what was expected
2. \p{scx=Arab} didn't work right.
The solution to these was to (1) allow for "" properly as a string value, and (2) allow script values that were not present in ScriptExtensions.txt as single values.
UnicodeJsps/src/main/java/org/unicode/jsp/ScriptTester.java
- Supply the Script values in addition to the Script_Extension values as valid alternate aliases.
UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeSetUtilities.java
- Expand an empty value to be "No" only for binary, enumerated, and catalogue properties
UnicodeJsps/src/main/java/org/unicode/jsp/XPropertyFactory.java
- main change is to allow "" as the default value in the scx map …
=> Fix remaining issues with multivalued

docs/unicodejsps/gcp-run.md, docs/unicodejsps/index.md
- improvement to gcp build docs
=> docs(jsp): update docs concerning GCR  #556

unicodetools/src/main/java/org/unicode/text/UCD/MakeUnicodeFiles.java
https://github.com/unicode-org/unicodetools/issues/627
Adds option to clean directory before building, then copy relevant files after building, as per issue
=> Add MakeUnicodeFiles.java option

unicodetools/src/main/java/org/unicode/text/UCD/GenerateConfusablesCopy.java, unicodetools/src/main/java/org/unicode/text/UCD/IdentifierInfo.java, unicodetools/src/main/java/org/unicode/text/UCD/TestUnicodeInvariants.java, unicodetools/src/main/java/org/unicode/text/UCD/VersionedProperty.java
Towards #432 and #502.
I want to do #432 (versioned property support in the JSPs) together with #502 (using unicodetools properties rather than ICU properties and properties badly reverse-engineered from ICU in the JSPs), otherwise we would lose the capability to have β properties.
That means splitting out the VersionedProperty class which is currently in the invariants test to someplace more reasonable for use in the JSPs.
I am trying to make this a « no functional change » PR, so while I am touching weird usages in UTS39-related generators that were reaching into the tests, I am not going to try to improve those.
The changes to VersionedProperty are minimal to get things to compile. They are quite hard to review because of the move, so I want to make any meaningful changes (and I will …
=> Move VersionedProperty to its own file

unicodetools/src/main/java/org/unicode/text/UCD/UCD_Names.java, unicodetools/src/main/java/org/unicode/text/UCD/UCD_Types.java
The same procedure as #443.
See L2/24-004 and L2/24-013.
=> Another script from the future

unicodetools/src/main/java/org/unicode/props/UcdProperty.java, unicodetools/src/main/java/org/unicode/props/UcdPropertyValues.java, unicodetools/src/main/resources/org/unicode/props/ExtraPropertyAliases.txt, unicodetools/src/main/resources/org/unicode/props/ExtraPropertyValueAliases.txt, unicodetools/src/main/resources/org/unicode/props/IndexUnicodeProperties.txt, unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt, unicodetools/src/test/java/org/unicode/propstest/TestProperties.java
Treat column 2 of ArabicShaping.txt as an unofficial contributory property and Joining_Type as a derived property in IndexUnicodePropertySource. When retiring ToolUnicodePropertySource, we should switch to using that derivation.
See [the test failure prior to the fix](https://github.com/unicode-org/unicodetools/pull/657/commits/616a9484cd1ad45308dce5e728eff44b5f928df6#diff-c2f2f053bbaa14f43053e3fb81a8afd67add46a4be1377d3e411f0500b40dabf).
=> Fix the IndexUnicodeProperties Joining_Type

unicodetools/data/ucd/dev/PropertyValueAliases.txt, unicodetools/src/main/java/org/unicode/props/UcdPropertyValues.java, unicodetools/src/main/java/org/unicode/text/UCD/MakeUnicodeFiles.java, unicodetools/src/main/java/org/unicode/text/UCD/ToolUnicodePropertySource.java
UTC-178-A13 Action Item for Mark Davis, PAG: Make the proposed change to PropertyValueAliases.txt to fix the long value alias for jg=Teh_Marbuta_Goal. For Unicode 16.0. See L2/24-009 item 2.6.
The code (with a function called "add unique") had inadvertently put the third alias into the slot for the long=second one because that happened to be the same as the first one.
=> UTC-178-A13: jg long alias Teh_Marbuta_Goal

UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeSetUtilities.java, unicodetools/src/main/java/org/unicode/props/UnicodeProperty.java, unicodetools/src/main/java/org/unicode/props/UnicodePropertySymbolTable.java, unicodetools/src/main/java/org/unicode/text/UCD/VersionedProperty.java, unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
Fix `getSet` so it correctly handles matchers that match `null`.
Make the `NULL_MATCHER` strict now that we distinguish `<none>` from empty strings.
Make the `NULL_MATCHER` public and special-case it for performance.
Make the syntax for the null matcher more consistent with already-sort-of-reserved syntax in UTS18 and UAX44 instead of making ∅ special. See unicode-org/properties#240.
Instead of `\p{Meow=/./}` for the set of code points for which `Meow` has a nonempty value, use `\P{Meow=@none@}` (the set of code points for which `Meow` has a value. This would include empty values, if there were any, though that is not relevant here.
=> Fewer regices

unicodetools/src/main/java/org/unicode/props/IndexUnicodeProperties.java, unicodetools/src/main/java/org/unicode/props/ShimUnicodePropertyFactory.java, unicodetools/src/main/java/org/unicode/props/UnicodeProperty.java, unicodetools/src/main/java/org/unicode/text/UCD/VersionedProperty.java
Resolve `#` in Name as well as `<code point>`, and return a correct UnicodeMap instead of one with unresolved defaults.
Factor out some other paths that had some other resolution logic.
Remove the corresponding shim, as well as the shims for the properties fixed in in #657 and #676.
=> Miscellaneous fixes to IUP

unicodetools/src/main/java/org/unicode/props/PropertyParsingInfo.java, unicodetools/src/main/java/org/unicode/props/ShimUnicodePropertyFactory.java, unicodetools/src/main/java/org/unicode/text/UCD/TestUnicodeInvariants.java, unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
Fix Jamo_Short_Name, which was incorrectly null instead of empty for U+110B HANGUL CHOSEONG IEUNG.
See [the test failure before the fix](https://github.com/unicode-org/unicodetools/pull/686/commits/6b234062b7a38f5b41c5fd207f2a03257169954f#diff-c2f2f053bbaa14f43053e3fb81a8afd67add46a4be1377d3e411f0500b40dabfR994).
Also rework the DSL a bit:
* Do not implicitly make the application of a non-string property to a string mean the _set_ of values, as this has misled Markus and me (we thought a binary property applied to a two-character string would yield YesYes or somesuch, see https://github.com/unicode-org/unicodetools/pull/673#discussion_r1473392606), and can readily lead to bugs since toNFWhatever was not treated as a string for these purposes! Instead make those return a sequence.
* …
=> Make the invariant tests a bit more understandable, test and fix IUP Jamo_Short_Name

unicodetools/src/main/java/org/unicode/text/UCD/TestUnicodeInvariants.java, unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
UTC-151-A143 **Action Item for** <del>Mark Davis, Laurențiu Iancu: </del><ins>Robin Leroy, Josh Hadley, PAG: </ins>Add invariant tests for new property and property values from PRI-344.
Add ∈ to in lines, since « the value of the Equivalent_Unified_Ideograph property of all of those things is a Unified_Ideograph » feels more readable than « the value of the Unified_Ideograph property of the value of the Equivalent_Unified_Ideograph property of all of those things is Yes ».
=> Some invariants for the Equivalent_Unified_Ideograph of radicals

pub/copy-alpha-to-draft.sh, pub/copy-beta-to-draft.sh, pub/copy-final.sh, unicodetools/data/emoji/dev/ReadMe.txt, unicodetools/data/ucd/dev/emoji/ReadMe.txt, unicodetools/data/ucd/dev/zipped-ReadMe.txt
by user demand since popular web browsers no longer support FTP
=> publish the UCD.zip in alpha & beta as well

unicodetools/src/main/java/org/unicode/props/UcdProperty.java, unicodetools/src/main/java/org/unicode/props/UcdPropertyValues.java, unicodetools/src/main/resources/org/unicode/props/ExtraPropertyAliases.txt
While playing with the staging JSPs which have Unihan properties since #659, @Manishearth had lamented the lack of kStrange.
=> Add Unihan properties from Unicode 14.0, 15.0, 15.1, and 16.0

c/uca/sifter/unisift.c, unicodetools/data/uca/dev/allkeys.txt
See the email thread titled « DUCET and UCD disagree on the size of the Tangut_Supplement block ».
DRAFT: on top of #713.
=> Fix the upper bound of the Tangut Supplement Block in the UCA

unicodetools/src/main/resources/org/unicode/props/IndexUnicodeProperties.txt
…thereby fixing the parsing of 17 properties in 3.2..4.1; see the 17 `3.2..4.1: null` in https://unicode-jsps-staging-o2ookmn2oq-uc.a.run.app/UnicodeJsps/character.jsp?a=3400&history=assigned&showDevProperties=1 for properties that were in PropList.txt.
Towards #650.
=> Fix pre-5.0 Grapheme_Link parsing

unicodetools/src/main/java/org/unicode/tools/AacOrder.java
AacOrder didn't give details about where its data came from.
Example output with this PR:
```
```
- Also, update the UCD version number to 15.1
=> feat: AacOrder should have a header with version numbers

unicodetools/data/ucd/dev/NamesList.txt, unicodetools/data/ucd/dev/Unikemet.txt
From KenW:
> Unikemet-16.0.0d11.txt
>
> That has a large number of updates from Michel, mostly to add missing
> kEH_UniK values for new characters (and move a few that were assigned to
> the wrong character).
>
> NamesList-16.0.0d15.txt
>
> Regenerated names list. As expected, there were no impacts from the
> Unikemet.txt changes, which hit property values not reflected in the
> names list. However, there were two xref values added, between two
> particularly notorious hieroglyph characters, one a fly in the old
> block, and one a fly in the new block -- two flies in our character
> ointment, so to speak.
🪰🪰
=> UCD 16.0: Updates for Unikemet.txt and NamesList.txt

unicodetools/data/ucd/dev/ScriptExtensions.txt, unicodetools/src/main/java/org/unicode/props/UnicodeProperty.java, unicodetools/src/main/java/org/unicode/text/UCD/MakeUnicodeFiles.java, unicodetools/src/main/resources/org/unicode/text/UCD/MakeUnicodeFiles.txt
The diff of ScriptExtensions.txt between main and this new format is obviously useless; however, I have reenacted the history of ScriptExtensions.txt since Unicode 15.0 in the commits of this pull request, so that we can see what diffs would look like in this format.
Compare:
| Old format diff | New format diff |
|---|---|
| 4bfab4a7 | d22e65b4cb836171308387b46bfcc4f0315aeb29 |
| [cab2fa7f](https://github.com/unicode-org/unicodetools/commit/cab2fa7f3329bb79f2ca1e0fee352d8d843cb169#diff-be644dcdee5300b7b7989cb4fdcc3dfe9b2d31451896ea5ca2816b11a5156113) | 4837b38ff730b901ee9fe189fbacd6374fda027d |
| [dac024cc](https://github.com/unicode-org/unicodetools/commit/dac024cc41488b38ff3a59a023bb318a68e2a370#diff-be644dcdee5300b7b7989cb4fdcc3dfe9b2d31451896ea5ca2816b11a5156113) | …
=> An alternative format for ScriptExtensions.txt

unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
See https://github.com/unicode-org/unicodetools/pull/708#discussion_r1522375203.
=> A name-based invariant about Lowercase

unicodetools/data/ucd/dev/ScriptExtensions.txt
[178-C29] Consensus: Add Kannada to the ScriptExtensions.txt entry for U+1CD3 VEDIC SIGN NIHSHVASA for Unicode Version 16.0 as described in L2/24-024. [Ref. Section 7 of document L2/24-013R]
[178-A80] Action Item for Roozbeh Pournader, PAG: Add the value Knda (Kannada) in ScriptExtensions.txt for U+1CD3 VEDIC SIGN NIHSHVASA for Unicode Version 16.0, based on document L2/24-024. [Ref. Section 7 of L2/24-013R]
=> Add Knda to scx for U+1CD3

unicodetools/data/ucd/dev/NamesList.txt
> UnicodeData-16.0.0d14.txt
>
> Just the name change for 31E4. Should match unicodetools.
And indeed it does, so no change on top of #783.
> NamesList-16.0.0d17.txt
> 
> New generation. Only updates the one name for 31E4.
(As noted by @markusicu, the updated UCA files should be done on top of #762.)
I will put EastAsianWidth-16.0.0d7.txt in a separate PR.
=> NamesList-16.0.0d17.txt

unicodetools/data/ucd/dev/NamesList.txt, unicodetools/data/ucd/dev/Unikemet.txt
I had noted the following about the NamesList change in #788:
> I see you added an annotation explaining the Mende Kikakui situation, per a UTC action item.
> 
> I think it would be useful to similarly add an annotation explaining the (similarly confusing, but, as noted in plenary, different) cuneiform situation; something like:
> 12326 CUNEIFORM SIGN UN
>      = KALAM gunû
>      * the names of this and the following sign incorrectly reflected the gunû relationship between them  
> 12327 CUNEIFORM SIGN UN GUNU
>       % CUNEIFORM SIGN KALAM
> One more update to the names list. For this, in addition to your suggested annotation for 12326, I picked up Michel's latest Unikemet.txt, with a bunch of fixes for misspellings in kEH_Func values and removal of extra spaces in …
=> Fresh UCD Kenfiles, batch 4

unicodetools/data/ucd/dev/PropList.txt
[[179-C21](https://www.unicode.org/cgi-bin/GetL2Ref.pl?179-C21)] Consensus: Remove the Terminal_Punctuation property from U+0836 SAMARITAN ABBREVIATION MARK. For Unicode Version 16.0. See document [L2/24-064](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/24-064) item 2.1.
[[179-A89](https://www.unicode.org/cgi-bin/GetL2Ref.pl?179-A89)] Action Item for Robin Leroy, PAG: In PropList.txt, remove the Terminal_Punctuation property from U+0836 SAMARITAN ABBREVIATION MARK. For Unicode Version 16.0. See document [L2/24-064](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/24-064) item 2.1.
=> Are abbreviation marks terminal punctuation? (No.)

unicodetools/data/ucd/dev/ScriptExtensions.txt
[179-C56] Consensus: Add Latn to the Script_Extensions property of U+1DF8 in the ScriptExtensions.txt file as documented in document L2/24-091 for Unicode Version 16.0. [Ref. Section 12 of document L2/24-068]
[179-A163] Action Item for Roozbeh Pournader, PAG: Add Latn to scx of U+1DF8, for Unicode Version 16.0. [Ref. Section 12 of document L2/24-068]
=> Add Latn to scx of U+1DF8

unicodetools/data/ucd/dev/NamesList.txt
> This took care of 3 more stray action items noted in the minutes, to add
annotations for 0B35, 0B55, and 1DF8 and to explain the use of colon in
the Egyptian function : value annotations.
To wit:
[[179-A87](https://www.unicode.org/cgi-bin/GetL2Ref.pl?179-A87)] Action Item for Ken Whistler, EDC: Fix the punctuation in NamesList.txt to a single space before the colon, and add an explanatory note to NamesList.txt . See ReportID ID20240402044338 in document [L2/24-065](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/24-065) item E2.
[[179-A156](https://www.unicode.org/cgi-bin/GetL2Ref.pl?179-A156)] Action Item for Ken Whistler, EDC: Add annotations to U+0B35 ORIYA LETTER VA, U+0B55 ORIYA SIGN OVERLINE as described in document …
=> Kenfiles, frisch vom Faß

unicodetools/data/security/dev/IdentifierStatus.txt, unicodetools/data/security/dev/IdentifierType.txt, unicodetools/data/security/dev/data/confusablesSummaryIdentifier.txt, unicodetools/data/security/dev/data/draft-restrictions.txt, unicodetools/src/main/java/org/unicode/props/UcdProperty.java, unicodetools/src/main/java/org/unicode/text/UCD/IdentifierInfo.java, unicodetools/src/main/resources/org/unicode/props/ExtraPropertyAliases.txt, unicodetools/src/main/resources/org/unicode/props/ExtraPropertyValueAliases.txt
[[179-A127](https://www.unicode.org/cgi-bin/GetL2Ref.pl?179-A127)] Action Item for Markus Scherer, PAG: In UTS #39 and its data files, define & document short property aliases ID_Status for Identifier_Status and ID_Type for Identifier_Type. For Unicode Version 16.0. See document [L2/24-064](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/24-064) item 8.3.
The generated, tool-internal data files also reflect the UTS46/IDNA data changes from the minimized base exclusion set.
=> short: ID_Status & ID_Type

unicodetools/data/ucd/dev/PropList.txt, unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
stolen from @macchiati:
[[178-A22](https://www.unicode.org/cgi-bin/GetL2Ref.pl?178-A22)] Action Item for Mark Davis, PAG: In PropList.txt, give U+2024 ONE DOT LEADER the Sentence_Terminal property. For Unicode Version 16.0. See [L2/24-009](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/24-009) item 6.3.
=> U+2024 Sentence_Terminal

unicodetools/data/ucd/dev/auxiliary/LineBreakTest.html, unicodetools/src/main/resources/org/unicode/tools/SegmenterDefault.txt
This rule, approved by UTC-179-C35, does nothing, because LB13 already did whatever it would do.
I will be putting a review note about that in the proposed update (see https://github.com/unicode-org/unicode-reports/pull/141), this obviously has no effect and will have been called out during review so I do not think it warrants a decision separate from the decision to approve UAX14 for final publication.
Also: add a missing space.
=> Remove a redundant rule

unicodetools/data/ucd/dev/PropList.txt, unicodetools/data/ucd/dev/auxiliary/SentenceBreakProperty.txt, unicodetools/src/main/java/org/unicode/text/UCD/ToolUnicodePropertySource.java
UTC-179-A114 | Josh Hadley | PAG | Update SentenceBreakProperty.txt, categorizing Semicolons and Greek Question Mark as SContinue, U+2CF9..U+2CFB as STerm, and Vertical Forms punctuation (U+FE10..U+FE19) in the same categories as their compatibility equivalents. For Unicode Version 16.0. See document L2/24-064 item 5.14.
UTC-179-A115 | Josh Hadley | PAG | In PropList.txt, add U+2CF9..U+2CFB to Sentence_Terminal. For Unicode Version 16.0. See document L2/24-064 item 5.14.
**NOTE 1**: "Semicolons" was not explicitly defined for UTC-179-A114, so I settled on "characters that have `SEMICOLON` in their name and are gc=Punctuation" for a definition.
**NOTE 2**: The Sentence Break property of U+2026, the compatibility equivalent of U+FE19 was "Other" (i.e. not explicitly defined), so no change …
=> Semicolons and Sentence Breaks

unicodetools/data/ucd/dev/ScriptExtensions.txt, unicodetools/src/main/resources/org/unicode/text/UCD/MakeUnicodeFiles.txt
Since PR #723 we print ScriptExtensions.txt data lines simply in code point order.
Therefore, we should remove the description of the old order of lines.
=> remove old claim of scx order by values

unicodetools/data/ucd/dev/SpecialCasing.txt, unicodetools/src/main/resources/org/unicode/text/UCD/SpecialCasingHeader.txt
[[176-A68](https://www.unicode.org/cgi-bin/GetL2Ref.pl?176-A68)] Action Item for Markus Scherer, Asmus Freytag, PAG: In the core spec, near Table 3-17 “Context Specification for Casing” and in chapter 5.18 “Case Mappings”, document that additional language-specific and orthography-specific case mapping behavior is or will be documented in CLDR; see also [L2/23-160](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/23-160) item 2.3; for Unicode 16.0.
=> SpecialCasing context/locale only historical

unicodetools/src/main/java/org/unicode/idna/GenerateIdna.java
Code version of
[[178-A25](https://www.unicode.org/cgi-bin/GetL2Ref.pl?178-A25)] Action Item for Markus Scherer, Mark Davis, PAG: In UTS#46 section 6 step 2 “Specify the base valid set” replace the removal of \p{Block=Ideographic_Description_Characters} and \u31EF with the removal of [\p{IDS_Unary_Operator}\p{IDS_Binary_Operator}\p{IDS_Trinary_Operator}]. For Unicode Version 16.0. See [L2/24-009](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/24-009) item 7.2.
=> UTS46 valid: use IDS not Block=IDC

unicodetools/data/ucd/dev/auxiliary/SentenceBreakProperty.txt, unicodetools/src/main/java/org/unicode/text/UCD/ToolUnicodePropertySource.java
pre-16.0 beta public [feedback](https://www.unicode.org/review/pri494/feedback.html#ID20240509103608) pointed out some issues with the [first pass](https://github.com/unicode-org/unicodetools/pull/812) at addressing UTC-179-A113. After some discussion with other PAG members, we decided to make the definition of "Semicolons" to be U+003B and its [compatibility equivalents](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3ADecomposition_Mapping%3D%3B%3A%5D&g=sb&i=).
=> Semicolons; revisited

unicodetools/data/ucd/dev/NamesList.txt
From Ken:
This adds in the formal name alias for the Bamum character 1680B. Michel noticed it was missing.
Except: Markus restored the "For terms of use **and license**" in the header.
=> NamesList-16.0.0d22.txt

unicodetools/data/idna/dev/IdnaTestV2.txt, unicodetools/src/main/java/org/unicode/idna/GenerateIdnaTest.java, unicodetools/src/main/java/org/unicode/idna/Uts46.java
[[165-A48](https://www.unicode.org/cgi-bin/GetL2Ref.pl?165-A48)] Action Item for Markus Scherer, Editorial Committee: Update UTS#46 to validate ACE label edge cases, see [L2/20-240](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/20-240) item F7. For Unicode 14.
Corresponds to spec change
- https://github.com/unicode-org/unicode-reports/pull/149
The IDNA2008 ToUnicode operation validates ACE labels ("xn--" plus Punycode)
by decoding them, then re-encoding via ToASCII, and verifying that the
round-trip output is the same as the input (case-insensitive).
The UTS#46 ToUnicode operation and its Processing step uses a cheaper
Convert/Validate step which wants to be equivalent.
However, it misses two edge cases which pass Convert/Validate step but which
IDNA2008 catches with its …
=> idnatest error if xn-- empty or all-ASCII

unicodetools/data/idna/dev/IdnaTestV2.txt, unicodetools/src/main/java/org/unicode/idna/GenerateIdnaTest.java
=> idnatest with NormalizationCorrections

unicodetools/data/idna/dev/IdnaTestV2.txt, unicodetools/src/main/java/org/unicode/idna/GenerateIdnaTest.java
Fixes #747
@hsivonen wrote:
IdnaTestV2.txt missed a bug in the UTS 46 implementation that I'm writing due to not testing an upper-case letter in the ASCII part of Punycode when there are no errors.
I suggest adding this test case.
=> idnatest Punycode with uppercase ASCII

.github/workflows/cli-build-instructions.yml, unicodetools/src/main/java/org/unicode/text/UCD/TestUnicodeInvariants.java, unicodetools/src/main/resources/org/unicode/text/UCD/SecurityInvariantTest.txt, unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt, unicodetools/src/test/java/org/unicode/text/UCD/TestTestUnicodeInvariants.java
See discussion in PAG meeting 2024-05-23.
See it in action in https://github.com/unicode-org/unicodetools/pull/833/files#diff-ae46290feceee5ef92cbfa7106806971b53e015ab3f842e6d1bd9f816dbb9958.
=> Move the security invariants to their own CI check

unicodetools/data/ucd/dev/ScriptExtensions.txt, unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
For https://www.unicode.org/review/pri502/feedback.html#ID20240523095709 (https://github.com/unicode-org/properties/issues/296).
=> Hani CJK strokes

unicodetools/data/ucd/dev/DoNotEmit.txt
The file header had a misspelling: Egyptial instead of Egyptian.
https://github.com/unicode-org/properties/issues/295#issuecomment-2130313812
=> Fix typo in DoNotEmit.txt comments

docs/build.md, unicodetools/src/main/java/org/unicode/text/UCD/TestUnicodeInvariants.java, unicodetools/src/test/java/org/unicode/text/UCD/TestTestUnicodeInvariants.java
Among other things, #834 broke the reporting of invariant test failures in the diff.
Cherry-picked from https://github.com/unicode-org/unicodetools/pull/839 which will take longer to merge because it has a property change.
=> Fix some bugs in the splitting of the invariants

unicodetools/data/ucd/dev/NamesList.txt
> I've done another generation of NamesList.txt, with the first of the
additions after we started beta review. I'm calling it a post-beta, and
anticipate there will end up being more updates needed as beta review
feedback comes in.
>
> This first change was for an old action item, 164-A42, which was to deal
with Rebecca's feedback in L2/20-158. SAH had taken a look at it, and at
the time, back in 2020, decided it was too much for the names list
annotations, and asked me to look at whether it made sense for text
additions to 22.7 in the core spec, or just as fodder for a UTN. After
thinking about this a bit, it turns out this really is special
information about 3 particular characters. Trying to provide enough
context in an explanation for Section 22.7 would just be …
=> NamesList update for UTC-164-A42

unicodetools/data/ucd/dev/DoNotEmit.txt
The language around these in the Core Spec is being changed and softened. It was agreed in SEW to remove them from DoNotEmit.
=> Remove Egyptian Hieroglyphs from DoNotEmit

unicodetools/data/ucd/dev/NamesList.txt
> This incorporates a number of subhead fixes for the new Egyptian
Hieroglyphs block, noted by Michel Mariani and verified by Michel
Suignard (so they have a double-Michel imprimatur). I also rolled in a
fix for an out-of-place subhead in Garay noted by Peter C, and a couple
of xrefs requested by Charlotte Buff.
> 
> I may have missed something, but I think this catches the names list
annotations up with recent feedback.
=> NamesList-16.0.0d25.txt

unicodetools/src/main/java/org/unicode/text/UCD/TestUnicodeInvariants.java, unicodetools/src/main/resources/org/unicode/text/UCD/SecurityInvariantTest.txt, unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
See https://github.com/unicode-org/unicodetools/pull/855#discussion_r1629990475 sqq.
Since Markus wanted := rather than ≔ this takes a bit of restructuring of the parser; I wrote it in a way that should avoid running into the C++03 >> problem in the future.
=> Use := for definitions in the invariant tests

unicodetools/data/ucd/dev/NamesList.txt, unicodetools/data/ucd/dev/StandardizedVariants.txt, unicodetools/data/ucd/dev/Unikemet.txt, unicodetools/src/test/java/org/unicode/propstest/TestInvariants.java
> I've picked up the latest round of fixes for Unikemet.txt from Michel,
which should bring us up to date on all the feedback provided on that file.
> 
> I also jumped the gun a bit and implemented the changes for the
hieroglyph rotation standardized variation sequences in
StandardizedVariants.txt.
> 
> https://github.com/unicode-org/sah/issues/378
> 
> The reason to move ahead on these items right away is that they involve
a lot of moving parts for the Egyptian chart generation, and we need to
shake this all down ASAP. This work also involves changes by Michel for
the Unibook configuration file to properly highlight these changes, as
well as changes for new formal name aliases.
> 
> I've regenerated NamesList.txt using the updated Unikemet.txt and …
=> Hieroglyphic Kenfiles

unicodetools/src/main/java/org/unicode/text/UCD/UCD_Names.java, unicodetools/src/main/java/org/unicode/text/UCD/UCD_Types.java
Same procedure as https://github.com/unicode-org/unicodetools/pull/660, but this time it has been in ISO 15924 for a while so no need for private use.
=> Yet another script from the future

unicodetools/data/ucd/dev/ScriptExtensions.txt
[UTC-180-C11] Consensus: Add Duployan (Dupl) to the Script_Extensions of U+00B7 MIDDLE DOT, U+0307 COMBINING DOT ABOVE, U+0308 COMBINING DIAERESIS, U+030A COMBINING RING ABOVE, U+0323 COMBINING DOT BELOW, U+0324 COMBINING DIAERESIS BELOW, and U+2E3C STENOGRAPHIC FULL STOP. For Unicode 16.0. See L2/24-162 item 1.5 and PRI-502#ID20240522040217.
[UTC-180-A40] Action Item for Roozbeh Pournader, PAG: Add Duployan (Dupl) to the Script_Extensions of U+00B7 MIDDLE DOT, U+0307 COMBINING DOT ABOVE, U+0308 COMBINING DIAERESIS, U+030A COMBINING RING ABOVE, U+0323 COMBINING DOT BELOW, U+0324 COMBINING DIAERESIS BELOW, and U+2E3C STENOGRAPHIC FULL STOP. For Unicode Version 16.0. See L2/24-162 item 1.5.
=> Add Duployan to Script_Extensions for various characters

unicodetools/data/ucd/dev/ArabicShaping.txt, unicodetools/data/ucd/dev/PropertyValueAliases.txt, unicodetools/data/ucd/dev/extracted/DerivedJoiningGroup.txt, unicodetools/src/main/java/org/unicode/props/UcdPropertyValues.java, unicodetools/src/main/java/org/unicode/text/UCD/UCD_Names.java, unicodetools/src/main/java/org/unicode/text/UCD/UCD_Types.java
[UTC-180-C24] Consensus: In ArabicShaping.txt, change the Joining_Group for U+0620 from YEH to a new joining group KASHMIRI YEH, and change its schematic name from DOTLESS YEH WITH SEPARATE RING BELOW to KASHMIRI YEH for Unicode 16.0. [Ref. Section 3b of L2/24-166]
[UTC-180-A69] Action Item for Roozbeh Pournader, PAG: Update ArabicShaping.txt for U+0620 per L2/24-152 for Unicode 16.0. [Ref. Section 3b of L2/24-166]
[UTC-180-A70] Action Item for Roozbeh Pournader, PAG: Update PropertyValueAliases.txt with the new joining group for Kashmiri Yeh. [Ref. Section 3b of L2/24-166]
=> Update ArabicShaping for Kashmiri Yeh

unicodetools/data/ucd/dev/NamesList.txt
> I have regenerated NameList.txt with the latest StandardizedVariants.txt
> and Unikemet.txt, and with annotations added for 2217 ([180-A104](https://www.unicode.org/cgi-bin/GetL2Ref.pl?180-A104)) and for
> mentioning UTN #&zwnj;57 in the Mongolian block ([180-A4](https://www.unicode.org/cgi-bin/GetL2Ref.pl?180-A4)).
> The delta should show up as only two point changes and the notes in the
> header section.
And indeed it does.
> I've closed [180-A4](https://www.unicode.org/cgi-bin/GetL2Ref.pl?180-A4) and [180-A104](https://www.unicode.org/cgi-bin/GetL2Ref.pl?180-A104) for this. I'm also closing my action
> [180-A107](https://www.unicode.org/cgi-bin/GetL2Ref.pl?180-A107) to provide an updated NamesList.txt for 16.0, as I have no
> further related actions for 16.0 names …
=> NamesList-16.0.0d28.txt

pub/copy-beta-to-draft.sh
The path to the "sed" script was wrong, and I overlooked the error message in the console output, so the placeholders didn't get processed :-(
Not a problem in the final-release publication script. In fact, I had copied the "sed" command from that script to the beta script and failed to adjust for the different path names.
=> pub beta CollationTest.html: fix placeholders

unicodetools/src/main/java/org/unicode/text/UCD/TestUnicodeInvariants.java, unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt, unicodetools/src/test/java/org/unicode/text/UCD/TestTestUnicodeInvariants.java
See https://www.unicode.org/reports/tr35/#unicodeset-syntax, `\N{whatever}` is a `quoted`, which is a `char`, which is an `element`, so one should be able to use it in a `range`.
ICU treats it a a synonym for `\p{Name=whatever}`, which is a `unicodeSet`, so that the thing that should be a range is a set difference (equal to its LHS in practice).
That also means that `\N{nonexistent name}` is silently empty.
We should fix it in ICU, but we urgently need to fix it here for UCD development, because _we have already been bitten by it_, with no-one noticing; the following only tests the first letter of the Garay alphabet:
https://github.com/unicode-org/unicodetools/blob/cccbe935932337bc7f87b8a7b151d6e2fcf78a17/unicodetools/src/main/resources/org/unicode/text/UCD/AdditionComparisons.txt#L27-L34
=> Work around a UnicodeSet bug

unicodetools/data/uca/dev/CollationTest/CollationTest_NON_IGNORABLE_SHORT.txt, unicodetools/data/uca/dev/CollationTest/CollationTest_SHIFTED_SHORT.txt, unicodetools/src/main/java/org/unicode/draft/GenerateUnihanCollators.java, unicodetools/src/main/java/org/unicode/text/UCA/RadicalStroke.java
Make the CLDR radical-stroke order of CJK ideographs match the order in [UAX38 section 2.1.2 Sorting Algorithm Used by the Radical-Stroke Indexes](https://www.unicode.org/reports/tr38/#SortingAlgorithm).
For
- CLDR-17224 FractionalUCA.txt: review radical-stroke order / re: simplified radicals
- https://github.com/unicode-org/unicodetools/issues/620
Changes:
- Change the 64-bit encoding of the sort order, moving the simplified-ness field below the number of residual strokes.
- As a result, the traditional and simplified forms of characters are intermingled.
- Therefore, any output by radical changes from multiple "buckets" like 182, 182', 182'' to a single "bucket" for radical 182.
- Code-wise, many places that used to work with a radicalNumberAndSimplified now just work with the …
=> make CLDR radical-stroke order = UAX38

unicodetools/data/ucd/dev/NamesList.txt
From Ken:
I have done the step to clean out all the intermediate change notes and mark NamesList.txt final for 16.0.
No substantive changes to any of the content of the NamesList.txt file that appears in charts.
=> Unicode 16 final NamesList

unicodetools/data/ucd/dev/NamesList.html
From Ken:
It turns out nobody ever updated NamesList.html (at all) for the beta review. The copy you have still claims it is Unicode 15.1.0. I've just done a pro forma update to version 16.0.0.
FYI, related:
- https://github.com/unicode-org/properties/issues/122
=> Unicode 16 final NamesList.html

unicodetools/src/main/java/org/unicode/text/UCA/RadicalStroke.java
While updating ICU to the latest Unicode 16 files, I got collation conformance test failures. The CollationTest files are generated with the implicit-weights Han sort order and already omit Han characters that are known to sort differently in that sort order vs. radical-stroke order.
With the recent change to make the CLDR radical-stroke order match the one in UAX38 (unicodetools PR #909), we need to omit some more characters. Characters with traditional and simplified radicals are now intermingled, and some of them now sort differently in implicit-Han vs. radical-stroke order. I changed the CollationTest generator to omit all of the simplified radicals.
No DUCET CollationTest file changes.
Related:
- https://github.com/unicode-org/cldr/pull/3967
- …
=> CLDR CollationTest: omit simplified radicals

unicodetools/src/main/java/org/unicode/tools/emoji/CandidateData.java, unicodetools/src/main/java/org/unicode/tools/emoji/Emoji.java, unicodetools/src/main/java/org/unicode/tools/emoji/GenerateEmoji.java
When building emoji 16.0 charts I remembered/discovered that the latest Unicode version was only used during beta. Remove the `IS_BETA` checks for everything but human-readable text and rename `LATEST` to `PROPS`. I’m leaving most other variables alone in case we want to bring back the ability to build charts for the previous version.
=> Always use latest Unicode version when building emoji

unicodetools/src/main/java/org/unicode/text/UCA/UCA.java, unicodetools/src/main/java/org/unicode/text/UCA/WriteAllkeys.java
Fixes
- CLDR-17161 "v44 allkeys_CLDR.txt contains variable collation elements with an ignorable primary weight"
- https://github.com/unicode-org/unicodetools/issues/572
Primary weights above the special one for U+FFFE and up to variableTop are variable. Ignorable CEs with primary=0 are not variable.
Remove the "variable if last CE was" logic, and don't tell a function on class UCA where its own variableTop is.
Output:
- https://github.com/unicode-org/cldr/pull/3983
=> allkeys.txt ignorables are not variable

unicodetools/src/main/java/org/unicode/tools/emoji/GenerateEmoji.java
For
- https://github.com/unicode-org/unicodetools/issues/700
=> Add variation selectors to emoji alt attributes (#700)

unicodetools/src/main/resources/org/unicode/props/IndexUnicodeProperties.txt
In the unicodetools meeting of 2024-09-03, it came to our attention that Indic_Positional_Category used to be a provisional property called Indic_Matra_Category, renamed in UTC-140-C16 and then made informative in UTC-140-C17, for Unicode Version 8.0.
Just like we parse Indic_Syllabic_Category in versions where it was provisional, and expose it in historical views of property assignments, we should parse the provisional Indic_Matra_Category.
It seems most convenient to treat IndicMatraCategory.txt as defining InPC, since there are often no changes in assignment at the time of the renaming (specifically, `\P{U8.0:Indic_Positional_Category=@U7.0:Indic_Positional_Category@}-\p{U7.0:Indic_Positional_Category=NA}` (the set of characters that changed InPC from non-NA in 8.0) has cardinality 7, …
=> Parse IndicMatraCategory.txt

unicodetools/src/main/java/org/unicode/text/UCD/TestUnicodeInvariants.java, unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
Needed to test https://github.com/unicode-org/unicodetools/pull/885.
The strings are considered only as property values, their properties (whatever that means) are not looked at.
=> Allow strings in propertywise tests

.github/workflows/build-jsp.yml, .github/workflows/push-jsp-on-tag.yml
https://github.com/unicode-org/unicodetools/pull/931 failed with
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```
Doing that in a separate PR since it has nothing to do with 17.
=> Unbreak the workflows

docs/emoji/aac.md, unicodetools/src/main/java/org/unicode/tools/AacOrder.java
Make it easier for anyone to run the tool.
=> Stop manually setting versions in AacOrder.java

unicodetools/src/main/java/org/unicode/text/UCD/UCD_Names.java, unicodetools/src/main/java/org/unicode/text/UCD/UCD_Types.java
Same procedure as https://github.com/unicode-org/unicodetools/pull/888, as this one already has a script code.
=> The most ancient script from the future

.github/workflows/pythonpackage.yml
See https://devguide.python.org/versions/; the Python workflow started to fail.
=> Python 3.8 reached eol

unicodetools/data/ucd/dev/auxiliary/GraphemeBreakTest.html, unicodetools/data/ucd/dev/auxiliary/GraphemeBreakTest.txt, unicodetools/data/ucd/dev/auxiliary/LineBreakTest.html, unicodetools/src/main/java/org/unicode/text/UCD/GenerateBreakTest.java
This would have caught ICU-22956.
See also https://github.com/unicode-org/icu/pull/3257.
=> Test InCB=Extend for Gujarati Shadda

.github/workflows/cache_retain.yml
Mostly a nice-to-have adjustment that prevents the workflow from running in personal forks. When that happens, Github will complain about running a scheduled workflow on a repo with > 60 days of inactivity
=> Only run Maven cache workflow on the upstream repo

unicodetools/src/main/java/org/unicode/props/PropertyUtilities.java
Related to #419; redundant lines in Scripts.txt due to multiple changes affecting the same range caused an error. I think this one uses one of the newer parsers, which would explain why conflicts in the other data files didn’t run into it.
Note that since files get regenerated and we check that they have been regenerated, we shouldn’t actually end up with redundant lines.
=> Allow redundant lines in data files to facilitate merging

unicodetools/data/ucd/dev/NamesList.txt
(d4)
> I have done a first pass on getting a usable NamesList.txt for 17.0. […]
> This is generated against my version of the 17.0 UnicodeData.txt (UnicodeData-17.0.0d1.txt […]) and an initial drop of StandardizedVariants.txt (StandardizedVariants-17.0.0d1.txt […]), and the 16.0 version of Unikemet.txt.
> I manually synched the annotations against the 7th ed CD, and then updated further using Michel's latest delta names list file (which also includes most of the 18.0 anticipated repertoire). Then I also rolled in most of my action items for names list annotations for 17.0.
> Michel will notice that I did some pretty extensive editing of the annotations, particularly for the various content re phonetic characters from Kirk Miller. Hopefully, the result is better, but of …
=> NamesList-17.0.0d8.txt

unicodetools/data/ucd/dev/StandardizedVariants.txt
Notes from @Ken-Whistler:
It includes the 42 new standardized variation sequences for hieroglyphs, per UTC-181-C46 and my UTC-181-A115, interpolated in code point order into the previous list. I had to correct the hieroglyph names in the comments for the last 9 sequences. The data in L2/24-228 was using a pattern "EGYPTIAN HIEROGLYPH U+13BE8" for the names instead of the correct "EGYPTIAN HIEROGLYPH-13BE8", etc.
=> StandardizedVariants-17.0.0d1.txt

docs/data-workflow.md, pub/copy-ucd-to-draft.sh
Pruned version of the copy-alpha-to-draft.sh script. No security/IDNA/emoji files.
Related to @lianghai’s Charts issue
- https://github.com/unicode-org/charts/issues/30
=> script: publish early UCD snapshot

unicodetools/src/main/java/org/unicode/text/UCA/MakeNamesChart.java, unicodetools/src/main/java/org/unicode/text/UCA/WriteCharts.java, unicodetools/src/main/java/org/unicode/text/UCD/GenerateCaseFolding.java, unicodetools/src/main/java/org/unicode/text/UCD/GenerateConfusables.java, unicodetools/src/main/java/org/unicode/text/UCD/GenerateConfusablesCopy.java, unicodetools/src/main/java/org/unicode/text/UCD/GenerateNamedSequences.java, unicodetools/src/main/java/org/unicode/text/UCD/GenerateStandardizedVariants.java, unicodetools/src/main/java/org/unicode/text/UCD/MakeUnicodeFiles.java, unicodetools/src/main/java/org/unicode/text/UCD/UseTransliterator.java, unicodetools/src/main/java/org/unicode/text/utility/Settings.java, unicodetools/src/main/java/org/unicode/text/utility/UnicodeDataFile.java, unicodetools/src/main/resources/org/unicode/text/UCD/AdditionComparisons/154.txt, unicodetools/src/test/java/org/unicode/text/UCD/TestTestUnicodeInvariants.java
See https://github.com/unicode-org/utc-release-management/issues/154.
Also get rid of some static variables whose initialization was unreliable.
=> Fix placeholder name for addition comparison test

.github/workflows/build-jsp.yml
Fixes: #1007 
- automatically, on tag (or release), push a Docker image to Github packages (see: https://github.com/srl295/unicodetools/pkgs/container/unicodetools/345094535?tag=5.4.3.2.1-srltest )
- change the JSP build to be on-PR instead of on-push
- also updates some action versions
=> jsp: publish Docker Image to Github Packages on tag

unicodetools/src/main/resources/org/unicode/tools/SegmenterDefault.txt
Alternatives are left-to-right, not greedy: In the string
\<U+2E09 LEFT TRANSPOSITION BRACKET, U+2E0D RIGHT RAISED OMISSION BRACKET, U+1F3FC EMOJI MODIFIER FITZPATRICK TYPE-3>,
Searching for `( ^ | [^[\p{ea=F}\p{ea=W}\p{ea=H}]] ) \p{Line_Break=Quotation}` will find a match consisting of the first character, whereas searching for `( [^[\p{ea=F}\p{ea=W}\p{ea=H}]] | ^ ) \p{Line_Break=Quotation}` will find a match consisting of the first two characters.
ICU depends on a maximal match in its generated old monkeys: https://github.com/unicode-org/icu/blob/02951053b45f270c04ffeac6e0787dd2313bbd23/icu4c/source/test/intltest/rbbitst.cpp#L1779. This is messy to solve in general, but our alternatives here are simple enough that we can make them greedy by moving sot at the end.
Specifically, this …
=> Greedy context before in LB20a

unicodetools/data/ucd/dev/TangutSources.txt
From Michel Suignard:
From previous, the preamble has been updated to better reflect content (after work on the new UAX#60) and the last line concerning U+18D1E:
```
U+18D1E            kRSTUnicode    579.15
```
----
[[182-A38](https://www.unicode.org/cgi-bin/GetL2Ref.pl?182-A38)] Action Item for Robin Leroy, Michel Suignard, PAG: Update the Radical Stroke index of U+18D1E TANGUT IDEOGRAPH-18D1E from 579.14 to 579.15 For Unicode Version 17.0 as per [L2/25-040](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/25-040). [Ref. 3.1 in [L2/25-010](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/25-010)]
=> TangutSources uni17 jan28

UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeJsp.java, UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeUtilities.java, UnicodeJsps/src/main/java/org/unicode/jsp/XPropertyFactory.java, UnicodeJsps/src/main/webapp/properties.jsp, unicodetools/src/main/java/org/unicode/props/UnicodeProperty.java
Four commits, deployed in three builds of the JSPs:
1. Drop properties.jsp (we should bring something like it back eventually, but besides its abysmal performance it had not been seriously maintained and was becoming borderline useless);
2. Remove links to UnicodeSet queries for multivalued properties from character.jsp (these queries are very slow as currently implemented—minutes for some of the worst offenders—, and the link was to an invalid query when the character being inspected actually had multiple values anyway);
3.
* Remove the ICU-based toLowercase etc. pseudoproperties (these are from before the JSPs showed the real Lowercase_Mapping etc. properties, and UnicodeSet queries to compute the preimage of a function are intrinsically very slow);
* Fail multivalued Unihan property …
=> Bring back the JSPs

unicodetools/data/ucd/dev/emoji/emoji-data.txt, unicodetools/src/main/java/org/unicode/tools/emoji/GenerateEmojiData.java, unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
**[[182-C20](https://www.unicode.org/cgi-bin/GetL2Ref.pl?182-C20)] Consensus:** Unassign the Extended_Pictographic property from the 672 assigned characters that do not have the Emoji property. For Unicode Version 17.0. See [L2/25-006](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/25-006) item 5.1.
**[[182-A57](https://www.unicode.org/cgi-bin/GetL2Ref.pl?182-A57)] Action Item for** Robin Leroy, PAG: In UCD file emoji-data.txt, unassign the Extended_Pictographic property from the 672 assigned characters that do not have the Emoji property. For Unicode Version 17.0. See [L2/25-006](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/25-006) item 5.1.
emoji-data.txt being generated from itself, this was done by regenerating it with the patch in …
=> No ExtPict for old symbols

unicodetools/data/ucd/dev/VerticalOrientation.txt
[[182-A97](https://www.unicode.org/cgi-bin/GetL2Ref.pl?182-A97)] Action Item for Markus Scherer, PAG: Change the Vertical_Orientation property values of U+2018 LEFT SINGLE QUOTATION MARK, U+2019 RIGHT SINGLE QUOTATION MARK, U+201C LEFT DOUBLE QUOTATION MARK, and U+201D RIGHT DOUBLE QUOTATION MARK from R to Tr, based on document [L2/25-028](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/25-028) and Section 16 of document [L2/25-009](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/25-009), for Unicode Version 17.0.
Starting with @Ken-Whistler 's VerticalOrientation-17.0.0d3.txt but that changed U+2017 DOUBLE LOW LINE instead of U+2019 RIGHT SINGLE QUOTATION MARK, so my second commit fixes these two. I intend to squash-and-merge these changes.
=> UCD 17 VerticalOrientation.txt jan29

pub/copy-beta-to-draft.sh
In PR #1017 I missed lowercasing the /Public/draft/UCA folder to .../uca; see L2/25-012 section 3.3.
=> beta pub to lowercase draft/uca

unicodetools/data/ucd/dev/emoji/emoji-data.txt, unicodetools/data/ucd/dev/emoji/emoji-variation-sequences.txt, unicodetools/src/main/java/org/unicode/tools/emoji/GenerateEmojiData.java
=> Revert to previous version string format (#1002)

unicodetools/src/main/java/org/unicode/props/PropertyParsingInfo.java
=> Fix misparsing of old binary defaults

unicodetools/src/main/java/org/unicode/text/utility/Settings.java
The same procedure as #702.
Unicode 17.0 BRS Α3b.
=> It’s α now.

unicodetools/data/ucd/dev/NamesList.txt
I just rolled in a bunch of annotations, per Edcom issues unicode-org/edcom#177, unicode-org/edcom#180,
unicode-org/edcom#186, unicode-org/edcom#209,
unicode-org/edcom#211. This makes some point edits for a few characters (U+01A3, U+0342, U+0674), and then adds a bunch of informative aliases to Sidetic letters and to Adlam letters.
=> NamesList-17.0.0d12.txt

unicodetools/data/ucd/dev/PropList.txt
**[[181-C50](https://www.unicode.org/cgi-bin/GetL2Ref.pl?181-C50)] Consensus:** Assign the Diacritic property to the modifier letters from the Phonetic Extensions Supplement block, namely U+1D9B..U+1DBE [ᶛᶜᶝᶞᶟᶠᶡᶢᶣᶤᶥᶦᶧᶨᶩᶪᶫᶬᶭᶮᶯᶰᶱᶲᶳᶴᶵᶶᶷᶸᶹᶺᶻᶼᶽᶾ], for Unicode Version 17.0. See [L2/24-224](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/24-224) item 2.3.
**[[181-A130](https://www.unicode.org/cgi-bin/GetL2Ref.pl?181-A130)] Action Item for** Robin Leroy, PAG: In PropList.txt, assign the Diacritic property to the modifier letters from the Phonetic Extensions Supplement block, namely U+1D9B..U+1DBE [ᶛᶜᶝᶞᶟᶠᶡᶢᶣᶤᶥᶦᶧᶨᶩᶪᶫᶬᶭᶮᶯᶰᶱᶲᶳᶴᶵᶶᶷᶸᶹᶺᶻᶼᶽᶾ], for Unicode Version 17.0. See [L2/24-224](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/24-224) item 2.3.
=> ᶛᶜᶝᶞᶟᶠᶡᶢᶣᶤᶥᶦᶧᶨᶩᶪᶫᶬᶭᶮᶯᶰᶱᶲᶳᶴᶵᶶᶷᶸᶹᶺᶻᶼᶽᶾ are diacritics

UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeSetUtilities.java, unicodetools/src/main/java/org/unicode/props/UnicodePropertySymbolTable.java, unicodetools/src/test/java/org/unicode/unittest/TestUnicodeSet.java
=> Centralize and fix age comparison

UnicodeJsps/src/main/java/org/unicode/jsp/UcdLoader.java, UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeSetUtilities.java, UnicodeJsps/src/test/java/org/unicode/jsptest/TestUnicodeSet.java, unicodetools/src/main/java/org/unicode/props/IndexUnicodeProperties.java, unicodetools/src/main/java/org/unicode/text/UCD/UCD_Names.java
The implementation used getSet with a non-null UnicodeSet parameter, which updated the parameter according to the most recent version of the UCD when using incremental properties.
Unfortunately incremental property storage isn’t nicely testable because turning it on messes with static (and even file) caches, and we cannot turn it on by default because of https://github.com/unicode-org/unicodetools/issues/716.
Also handle the alias Combining_Mark for the gc=M grouping. Apparently it was added in 6.1, see UTC-126-C1.
https://github.com/unicode-org/unicodetools/blob/d29babc389773d9a1630ceac82dc7e8c46e42d4b/unicodetools/data/ucd/6.1.0-Update/PropertyValueAliases.txt#L554 https://github.com/unicode-org/unicodetools/blob/d29babc389773d9a1630ceac82dc7e8c46e42d4b/unicodetools/data/ucd/6.0.0-Update …
=> Fix versioned GC groupings in the JSPs

UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeSetUtilities.java, UnicodeJsps/src/test/java/org/unicode/jsptest/TestUnicodeSet.java, docs/help/list-unicodeset.md, unicodetools/src/main/java/org/unicode/props/IndexUnicodeProperties.java, unicodetools/src/main/java/org/unicode/props/PropertyParsingInfo.java, unicodetools/src/main/java/org/unicode/props/UnicodeProperty.java
And treat Name_Alias as a Name alias in the JSPs.
=> LM2 Name and Name_Alias matching

UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeUtilities.java, unicodetools/src/main/java/org/unicode/props/UnicodeProperty.java
* Put a `<wbr>` between values of multivalued properties so exemplar doesn’t make https://util.unicode.org/UnicodeJsps/character.jsp?a=a stupidly wide.
* Add back yellowing on multivalued properties (which was accidentally removed by #1018, see, _e.g._,  kPrimaryNumeric in https://util.unicode.org/UnicodeJsps/character.jsp?a=5146&showDevProperties=1)
=> Miscellaneous character.jsp cleanups

unicodetools/data/ucd/dev/ArabicShaping.txt
For some reason, the Adlam characters were missing spaces before their schematic names. 
Reported by @miloush
=> Add spaces for Adlam characters to ArabicShaping.txt

unicodetools/src/main/java/org/unicode/props/UnicodeProperty.java
@josh-hadley found that after #1057, everything gets U+-escaped in the comments of https://github.com/unicode-org/unicodetools/blob/main/unicodetools/data/security/dev/data/review.txt.
The rule governing what gets escaped is
https://github.com/unicode-org/unicodetools/blob/83971c46797e9d9cc1cbd5443e1ea10e1eef3e02/unicodetools/src/main/java/org/unicode/text/UCD/GenerateConfusables.java#L177-L178
and the underlying symbol table is the one from TUP:
https://github.com/unicode-org/unicodetools/blob/83971c46797e9d9cc1cbd5443e1ea10e1eef3e02/unicodetools/src/main/java/org/unicode/text/UCD/GenerateConfusables.java#L130-L137
ICU UnicodeSet does not give us the possibility of distinguishing \p{X} from \p{X=} in applyPropertyAlias, thus [:C:] is [:C=:].
Recall:
* from UAX44, that ISO_Comment is …
=> Fix [:C:] getting interpreted as the entire code space

py/splitunihan.py
It looks like the linter got an update, and it is now annoyed at an unnecessary `global` (`_prop_data` is used but not assigned in `main()`).
=> Python lint

unicodetools/src/main/java/org/unicode/props/UnicodeProperty.java, unicodetools/src/main/java/org/unicode/text/UCD/VersionedSymbolTable.java, unicodetools/src/test/java/org/unicode/text/UCD/TestVersionedSymbolTable.java
Clearly our problem of proliferation of symbol tables will be solved by adding yet another one; so far not used, and tested against examples from the working draft UnicodeSet spec.
This should be able to replace most of the existing symbol tables as-is. It needs some tweaking before I can use it in the invariant tests, so that it can use the versioned ToolUnicodeProperties[^retire] in some circumstances.
Towards #1073 and #1074.
[^retire]: Yes, those ones: #639. We’re not retiring them just yet…
=> One symbol table to rule them all

unicodetools/data/ucd/dev/PropertyAliases.txt, unicodetools/data/ucd/dev/PropertyValueAliases.txt, unicodetools/src/main/java/org/unicode/props/UcdProperty.java, unicodetools/src/main/java/org/unicode/text/UCD/ToolUnicodePropertySource.java, unicodetools/src/main/resources/org/unicode/props/ExtraPropertyAliases.txt, unicodetools/src/main/resources/org/unicode/text/UCD/PropertyAliasesHeader.txt
**[[183-C28](https://www.unicode.org/cgi-bin/GetL2Ref.pl?183-C28)] Consensus:** Add the Informative properties kMandarin, kTotalStrokes, and kUnihanCore2020 to PropertyAliases.txt, with respective short aliases cjkMandarin, cjkTotalStrokes, and cjkUnihanCore2020. For Unicode Version 17.0. See [L2/25-087](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/25-087) item 1.5.
**[[183-A57](https://www.unicode.org/cgi-bin/GetL2Ref.pl?183-A57)] Action Item for** Robin Leroy, PAG: In UCD file PropertyAliases.txt, add the Informative properties kMandarin, kTotalStrokes, and kUnihanCore2020, with respective short aliases cjkMandarin, cjkTotalStrokes, and cjkUnihanCore2020. For Unicode Version 17.0. See [L2/25-087](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/25-087) item 1.5. …
=> kMandarin, kTotalStrokes, and kUnihanCore2020 in PropertyAliases.txt

UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeUtilities.java, UnicodeJsps/src/main/webapp/index.css, unicodetools/src/main/java/org/unicode/props/PropertyParsingInfo.java
PropList-2.1.8.txt includes a diff between Unilib properties and what it calls « UnicodeData ». The « UnicodeData » values appear to prefigure the 3.1 derivation for, e.g., Alphabetic, but without the Other_Alphabetic exceptions. Ignoring the Discrepancy heading means we currently take the union of the Unilib and « UnicodeData » sets, which is nonsense. The Unilib set is the more useful one for historical investigation, as it is consistent with the files included in 2.1.5 and 2.1.9 (whereas taking the « UnicodeData » set introduces massive discrepancies that are immediately reverted in 2.1.9).
Currently, `\P{U2.1.8:Alphabetic=@U2.1.9:Alphabetic@}` has 21226 code points, and `\P{U2.1.8:Alphabetic=@U2.1.5:Alphabetic@}` has 21236 code points, whereas …
=> Improvements to property history

unicodetools/data/ucd/dev/PropList.txt
[[183-C27](https://www.unicode.org/cgi-bin/GetL2Ref.pl?183-C27)] Consensus: Assign the Diacritic property to U+05A2 HEBREW ACCENT ATNAH HAFUKH, U+05C5 HEBREW MARK LOWER DOT, and U+05C7 HEBREW POINT QAMATS QATAN. For Unicode Version 17.0. See [L2/25-087](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/25-087) item 1.2.
[[183-A56](https://www.unicode.org/cgi-bin/GetL2Ref.pl?183-A56)] Action Item for Robin Leroy, PAG: In UCD file PropList.txt, assign the Diacritic property to U+05A2 HEBREW ACCENT ATNAH HAFUKH, U+05C5 HEBREW MARK LOWER DOT, and U+05C7 HEBREW POINT QAMATS QATAN. For Unicode Version 17.0. See [L2/25-087](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/25-087) item 1.2.
See also unicode-org/properties#381.
=> Three Hebrew diacritics

UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeJsp.java, UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeUtilities.java, unicodetools/src/main/java/org/unicode/props/UnicodeProperty.java, unicodetools/src/main/java/org/unicode/text/UCD/VersionedSymbolTable.java
* Allow for gaps in the existence (or at least nontriviality) of a property (or nonproperty). Some of those instances are bugs, see #1118, but some reflect reality, e.g., the vanishing of kSemanticVariant in 2.1.x (shown here for U+3400 in the tools with this change, and in UTN45). 
* Fix a bug reported by @macchiati which caused the tools to reject the [version-qualifier](https://www.unicode.org/reports/tr61/#version-qualifier) `U17.0α:`.
* Fix a bug which caused an error in the JSPs on queries on numeric properties for versions other than the current one.
=> Various fixes to versioned property utilities

unicodetools/data/ucd/dev/NamesList.txt
From Ken:
This incorporates a large number of legacy hieroglyph annotations from L2/25-110. Then there is an annotation added for 1AB3 (UTC-182-A40).
Unless some new issue turns up, this should be the names list we use for the beta chart generation.
=> Unicode 17 beta NamesList

unicodetools/data/ucd/dev/CaseFolding.txt, unicodetools/src/main/resources/org/unicode/text/UCD/CaseFoldingHeader.txt
[[183-A59](https://www.unicode.org/cgi-bin/GetL2Ref.pl?183-A59)] Action Item for Markus Scherer, PAG: In CaseFolding.txt, change the full case folding example from "MASSE"/"Maße" to "FUSS"/"Fuß". For Unicode Version 17.0. See [L2/25-087](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/25-087) item 1.6.
=> change CaseFolding example from MASSE to FUSS

unicodetools/data/ucd/dev/CJKRadicals.txt
Update the description of CJK radical numbers in CJKRadicals.txt to be consistent with the use of apostrophes per the kRSUnicode property. For Unicode Version 17.0. See L2/24-224 item 2.5.
=> [UTC-181-A132] update CJKRadicals.txt

unicodetools/data/ucd/dev/DoNotEmit.txt
UTC-183-A87 Action Item for Roozbeh Pournader, PAG: Add a reference to kEH_AltSeq in the comments of DoNotEmit.txt. For Unicode Version 17.0.
=> Refer to kEH_AltSeq in DoNotEmit.txt

unicodetools/data/ucd/dev/NamesList.txt
> I have regenerated NamesList.txt again with a minor fix for the placement of the subhead in the Cuneiform Numbers and Punctuation block before U+1244A.
=> NamesList-17.0.0d18.txt

unicodetools/src/main/java/org/unicode/text/UCA/WriteCharts.java
For the footer on each contents page of https://www.unicode.org/charts/beta/
- extend the copyright range to 2025
- update to the new standard "For terms of use and license..."
=> aux charts (c) 2025 & std ToU

pub/copy-beta-to-draft.sh, pub/copy-final.sh, unicodetools/data/uca/dev/ReadMe.txt
Draft & final folders have lowercase "uca" since 17 for consistency.
17 beta is the first time we publish UCA files, so I hadn't noticed until now that the zipping step was broken.
=> pub: UCA -> uca

unicodetools/src/main/java/org/unicode/text/UCA/MakeNamesChart.java, unicodetools/src/main/java/org/unicode/text/UCA/WriteCharts.java
- follow-up on
- #1148
- fixes copyright year range & ToU phrasing for NamesList charts
- uses the same footer as the other auxiliary charts
- un-hardcodes the copyright year range end
=> fix NamesList charts copyright footer

unicodetools/src/main/java/org/unicode/xml/AttributeResolver.java, unicodetools/src/main/java/org/unicode/xml/GeneratePropertyValues.java, unicodetools/src/main/java/org/unicode/xml/UCDXML.java, unicodetools/src/main/resources/org/unicode/uax42/fragments/Unikemet.xml, unicodetools/src/main/resources/org/unicode/uax42/output/tr42.html, unicodetools/src/main/resources/org/unicode/uax42/output/tr42.rnc
Fixed an issue where Unikemet properties weren't being applied correctly to ranges of characters. Improved handling of newlines and breaks in TR38/TR57.
=> Unikemet grouped property attributes and newlines in TR38/57

unicodetools/src/main/java/org/unicode/xml/UCDXML.java, unicodetools/src/test/java/org/unicode/propstest/CheckXmlProperties.java, unicodetools/src/test/java/org/unicode/propstest/XMLProperties.java
Fixed an issue with grouped noUnihan not showing nonCJK properties for Unihan range.
Updated CheckXmlProperties to work with UCDXML for 17.0
=> CheckXmlProperties and Grouped NoUnihan fix.

unicodetools/src/main/java/org/unicode/props/UcdProperty.java, unicodetools/src/main/java/org/unicode/xml/AttributeResolver.java, unicodetools/src/main/resources/org/unicode/props/IndexPropertyRegex.txt
Fix for https://github.com/unicode-org/properties/issues/435
Updated Unikemet regular expressions; however, RegEx for kEH_FVal doesn't validate against current data.
There are two issues:
1. The separator is ambiguous: "The delimiters '/' or '|' are used to separate alternative values..."
2. The syntax specifies letters and combining characters (e.g., h + COMBINING DOT BELOW [U+0323], rather than ḥ [U+1E25]). But Unikemet.txt in UCD uses the composed forms.
To avoid this for now, we'll treat kEH_FVal as SINGLE_VALUED.
I updated the rest of the Unikemet regular expressions from the latest version of UAX 57.
=> Updated Unikemet regular expressions and regenerated UCDXML

unicodetools/data/security/dev/IdentifierStatus.txt, unicodetools/data/security/dev/IdentifierType.txt, unicodetools/data/ucd/dev/CaseFolding.txt, unicodetools/data/ucd/dev/DerivedAge.txt, unicodetools/data/ucd/dev/DerivedCoreProperties.txt, unicodetools/data/ucd/dev/DoNotEmit.txt, unicodetools/data/ucd/dev/Jamo.txt, unicodetools/data/ucd/dev/NamedSequences.txt, unicodetools/data/ucd/dev/SpecialCasing.txt, unicodetools/data/ucd/dev/StandardizedVariants.txt, unicodetools/data/ucd/dev/TangutSources.txt, unicodetools/data/ucd/dev/extracted/DerivedName.txt, unicodetools/src/main/java/org/unicode/text/UCD/IdentifierInfo.java, unicodetools/src/main/resources/org/unicode/text/UCD/CaseFoldingHeader.txt, unicodetools/src/main/resources/org/unicode/text/UCD/DerivedAgeHeader.txt, unicodetools/src/main/resources/org/unicode/text/UCD/MakeUnicodeFiles.txt, unicodetools/src/main/resources/org/unicode/text/UCD/SpecialCasingHeader.txt
... so that we need not track section numbers changing as chapters and sections are inserted or reordered.
Exception: I have not tackled **ArabicShaping.txt** which has many section and table numbers, mostly in a table near the top, and without section/table names. **Could we remove this table of numbers?** The sections are easy to find by script name, and the relevant tables are all those that show contextually shaped glyphs.
- discussed, see [this comment below](https://github.com/unicode-org/unicodetools/pull/1178#issuecomment-3141514285)
----
The core specification is here: https://www.unicode.org/versions/latest/core-spec/
I refer to the "chapter-name" / "section-name" section when the chapter-name looks stable (e.g., "Conformance"), but only to the "section-name" when the …
=> make data files refer to core spec sections by name not number

unicodetools/data/ucd/dev/ScriptExtensions.txt
[UTC-184-A57] Action Item for Roozbeh Pournader, SAH: Update ScriptExtensions.txt to reflect the U+0331 COMBINING MACRON BELOW usage in Syriac, for Unicode Version 17.0. [Ref. 4.3 in L2/25-187]
=> Reflect use of Macron Below instead of Minus Below in Syriac in scx

unicodetools/data/security/dev/IdentifierType.txt, unicodetools/data/security/dev/data/source/removals.txt, unicodetools/src/main/java/org/unicode/text/UCD/IdentifierInfo.java
[[184-C33](https://www.unicode.org/cgi-bin/GetL2Ref.pl?184-C33)] Consensus: Change the Identifier_Type values for Gunjala Gondi characters (sc=Gong) from Limited_Use to Excluded, to match the UAX31 classification of the script. For Unicode Version 17.0. See [L2/25-183](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/25-183) item 6.4.
[[184-A76](https://www.unicode.org/cgi-bin/GetL2Ref.pl?184-A76)] Action Item for Josh Hadley, PAG: Derive the Identifier_Type values for Gunjala Gondi characters from the UAX31 classification of the script as specified. For Unicode Version 17.0. See [L2/25-183](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/25-183) item 6.4.
=> [UTC-184-A76] UAX31=Excluded ‬‭vs. ‬‭ID _ Type=Limited _ Use

unicodetools/data/ucd/dev/DoNotEmit.txt
[[184-A55](https://www.unicode.org/cgi-bin/GetL2Ref.pl?184-A55)] Action Item for Roozbeh Pournader, SAH: Add a comment to DoNotEmit.txt header explaining the situation with CJK compatibility characters. [Ref. 4.2 in [L2/25-187](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/25-187)]
=> Add comment about CJK compatibility ideographs to DoNotEmit.txt

docs/security/index.md
This is for the last part of
[[184-A77](https://www.unicode.org/cgi-bin/GetL2Ref.pl?184-A77)] Action Item for Mark Davis, PAG: Change UTS39 to request all feedback via the standard UTC reporting forms. Remove non-standard mechanisms from the Feedback reference and from other relevant parts of the spec. Change the formerly linked pages to point to the standard mechanism. **Change internal documentation to no longer refer to the special confusables suggestion mechanism.** For Unicode Version 17.0. See [L2/25-183](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/25-183) item 6.6.
See also
- https://github.com/unicode-org/properties/issues/6
- https://github.com/unicode-org/unicode-reports/pull/224
=> confusables: no more google forms for suggestions

docs/egg.md
This is intentionally not explaining the steps nor providing any options for other directory structures, running locally, etc. Those are found in the neighbouring index.md and gcp-run.md. Instead the point here is to have some reproducibility when it comes to pushing stuff to util.unicode.org, to avoid #1209 or similar mishaps.
See the minutes of the 2024-11-26 tools meeting, item 1h.
=> Document the exact process for pushing the JSPs from Windows
