unicode-org/unicodetools

- .github/workflows/build-charcheck.yml
- .github/workflows/build-jsp.yml
- .github/workflows/pythonpackage.yml
- c/char-check/.gitignore
- c/char-check/fetch-icu-bin.sh
workflows for:
- python lint check
- charcheck verify
- beginning of jsp build
code changes:
- charcheck: add code to fetch an Ubuntu binary
> add some actions

- UnicodeJsps/Dockerfile
> update tomcat version to 9.0.37

- UnicodeJsps/Dockerfile
- UnicodeJsps/WebContent/bidic.jsp
- build bidic (bidiref1) (separate alpine build)
- add a $BIDIREF1 env variable which gives the path to bidiref1
- does not set data path properly (yet)
Fixes #23
> CLDR-14145 fix bidic

- unicodetools/org/unicode/text/utility/Settings.java
- unicodetools/org/unicode/utilities/PolaritySet.java
- unicodetools/org/unicode/utilities/TestUnicodeSetParser.java
- unicodetools/org/unicode/utilities/UnicodeSetParser.java
CLDR dropped some settings that needed to be restored to get unicode tools to work. (Note: there is now a ticket to clean up both CLDR and UnicodeTools settings).
Added some test files for UnicodeSet.
> Fixed Setting, testing UnicodeSet parsing

- unicodetools/org/unicode/draft/GeneratePickerData2.java
- unicodetools/org/unicode/draft/IdnaLabelTester2.java
- unicodetools/org/unicode/draft/RadicalStroke2.java
- unicodetools/org/unicode/text/utility/Settings.java
- unicodetools/org/unicode/tools/emoji/EmojiImageData.java
Re-indented Settings.java, and left TODO referring to the CLDR cleanup ticket. 
Replaced failing compiles because of CLDR changes in 3 files.
> More Settings cleanup. 

- unicodetools/org/unicode/tools/Confusables.java
> Fix 2 errors in Confusables exposed by change in protectCollections

- unicodetools/org/unicode/tools/emoji/main-index.html
As requested by @kenlunde and temporarily patched by @rickmcgowan.
> Update link to Main Emoji Page

- unicodetools/.classpath
- unicodetools/org/unicode/text/UCD/MakeUnicodeFiles.txt
- unicodetools/org/unicode/text/UCD/UCD.java
- unicodetools/org/unicode/text/UCD/UCD_Types.java
Generated files at https://corp.unicode.org/~book/incoming/manishearth/u14/d9/
I have not pulled in new files from Public to minimize the diff.
> Add CJK ranges for Unicode 14

- unicodetools/data/emoji/14.0/ReadMe-ucd-emoji.txt
- unicodetools/data/emoji/14.0/ReadMe.txt
Not sure why the two files, but both now say “DRAFT” and reference 14.0.
> Update ReadMe files for Emoji 14.0

- docs/charts.md
- unicodetools/data/security/14.0.0/data/draft-restrictions.txt
- unicodetools/data/security/14.0.0/data/idnchars.txt
- unicodetools/data/security/14.0.0/data/source/removals.txt
based on partial review by UCD maintainers, and based on some action items
Only removals.txt is the real input here.
Other files are outputs.
> make some characters not recommended

- docs/emoji/index.md
- docs/index.md
- docs/newunicodeproperties.md
- docs/unihan.md
- docs/windows-setup.md
- unicodetools/org/unicode/draft/Cmudict.java
- unicodetools/org/unicode/draft/HanFrequencies.java
- unicodetools/org/unicode/text/UCA/WriteCharts.java
- unicodetools/org/unicode/text/UCD/ConvertUCD.java
- unicodetools/org/unicode/text/UCD/GenerateCaseFolding.java
- unicodetools/org/unicode/text/tools/CheckSecurityProposals.java
- unicodetools/org/unicode/text/utility/Settings.java
- unicodetools/org/unicode/tools/AacOrder.java
- unicodetools/org/unicode/tools/Confusables.java
- unicodetools/org/unicode/tools/FixedProps.java
- unicodetools/org/unicode/tools/emoji/Emoji.java
- unicodetools/org/unicode/tools/emoji/FixEmojiText.java
- unicodetools/org/unicode/tools/emoji/GenerateEmojiData.java
- unicodetools/org/unicode/tools/emoji/ListFonts.java
- reroute tools to source dirs or GEN_DIR
- add env var for the images repo, for some emoji output
- update docs
> remove env var for draft repo that no longer exists

- unicodetools/org/unicode/text/tools/RecommendedSetGenerator.java
This tool is used for Unicode version updates in ICU. (Shane wrote it.)
> RecommendedSetGenerator use latestVersion not hardcoded

- unicodetools/org/unicode/tools/emoji/ChartUtilities.java
- unicodetools/org/unicode/tools/emoji/GenerateEmoji.java
Rick noted that the link in the top bar of the pages in future/ go to the wrong page. As far as I can tell, this particular link is the only one that escapes that directory and needs to link to index.html in the sibling directory.
> Link to charts/index.html from pages in future/

- unicodetools/data/ucd/14.0.0-Update/BidiBrackets.txt
- unicodetools/data/ucd/14.0.0-Update/BidiMirroring.txt
- unicodetools/data/ucd/14.0.0-Update/CompositionExclusions.txt
- unicodetools/data/ucd/14.0.0-Update/NamedSequences.txt
- unicodetools/data/ucd/14.0.0-Update/NamedSequencesProv.txt
- unicodetools/org/unicode/draft/iana_character-sets.txt
- unicodetools/org/unicode/text/UCA/UCA.java
- unicodetools/org/unicode/text/UCD/GenerateBreakTest.java
- unicodetools/org/unicode/text/UCD/GenerateData.java
- unicodetools/org/unicode/text/UCD/TestData.java
- unicodetools/org/unicode/tools/emoji/ChartUtilities.java
These relied on old redirects.
> fix unicode.org/unicode/ URLs

- unicodetools/org/unicode/text/UCD/UnicodeInvariantTest.txt
> Unicode 14: adjust invariant test for new Lowercase modifier letters

- unicodetools/org/unicode/idna/GenerateIdnaTest.java
- unicodetools/org/unicode/idna/IdnaTestHeader2.txt
For action item 164-A52 In IdnaTestV2.txt, fix the URL .../tr46/proposed.html#Processing to point to the latest version of UTS 46
(also removed some trailing spaces)
> Unicode 14: temp hack in IdnaTestV2 generator, and URL fix

- unicodetools/org/unicode/text/UCD/MakeUnicodeFiles.txt
- unicodetools/org/unicode/tools/Segmenter.java
- unicodetools/org/unicode/tools/SegmenterCldr.txt
- unicodetools/org/unicode/tools/SegmenterDefault.txt
and harden the code against obscure bugs like this (fail fast)
> fix LineBreakTest ExtPictUnassigned

- unicodetools/data/emoji/14.0/ReadMe.txt
- unicodetools/data/emoji/14.0/emoji-sequences.txt
- unicodetools/data/emoji/14.0/emoji-test.txt
- unicodetools/data/emoji/14.0/emoji-zwj-sequences.txt
- unicodetools/data/ucd/14.0.0-Update/NamesList.html
- unicodetools/data/ucd/14.0.0-Update/emoji/ReadMe.txt
- unicodetools/data/ucd/14.0.0-Update/emoji/emoji-data.txt
- unicodetools/data/ucd/14.0.0-Update/emoji/emoji-variation-sequences.txt
copied verbatim from https://www.unicode.org/Public/
> Unicode 14 data files 20210903

- .github/workflows/build-charcheck.yml
- .github/workflows/pythonpackage.yml
Fixes #58
(note that #91 already corrects the Java part of this)
> adjust workflows to build all branches, not just 'master'/'main'

- .github/workflows/build-jsp.yml
- .github/workflows/push-jsp-on-tag.yml
- .settings/org.eclipse.core.resources.prefs
- UnicodeJsps/pom.xml
- pom.xml
> make UnicodeJsps depend on unicodetools

- unicodetools/src/test/java/org/unicode/propstest/TestXSet.java
- unicodetools/src/test/java/org/unicode/propstest/UnicodeRelationTest.java
- unicodetools/src/test/java/org/unicode/test/CaseBitTest.java
- unicodetools/src/test/java/org/unicode/tools/AacCheckTest.java
- unicodetools/src/test/java/org/unicode/tools/emoji/unittest/TestGender.java
- unicodetools/src/test/java/org/unicode/unittest/TestLocaleMatching.java
For: #146
Seemed to fail and has disabled subtests:
- CaseBitTest
I think all non-jsptest tests are now in JUnit.
Any remaining `main()`s weren't originally unit tests.
> test: missed some tests in mavenization

- unicodetools/src/main/java/org/unicode/idna/GenerateIdna.java
- unicodetools/src/main/java/org/unicode/idna/GenerateIdnaTest.java
- unicodetools/src/main/java/org/unicode/idna/LoadIdnaTest.java
- unicodetools/src/main/java/org/unicode/props/PropertyParsingInfo.java
- unicodetools/src/main/java/org/unicode/props/UcdProperty.java
- unicodetools/src/main/java/org/unicode/props/UcdPropertyValues.java
- unicodetools/src/main/java/org/unicode/props/VersionToAge.java
- unicodetools/src/main/java/org/unicode/text/UCA/UCA.java
- unicodetools/src/main/java/org/unicode/text/UCA/WriteCharts.java
- unicodetools/src/main/java/org/unicode/text/UCD/GenerateBreakTest.java
- unicodetools/src/main/java/org/unicode/text/UCD/GenerateConfusables.java
- unicodetools/src/main/java/org/unicode/text/UCD/GenerateConfusablesCopy.java
- unicodetools/src/main/java/org/unicode/text/UCD/GenerateData.java
- unicodetools/src/main/java/org/unicode/text/UCD/Main.java
- unicodetools/src/main/java/org/unicode/text/UCD/MakeUnicodeFiles.java
- unicodetools/src/main/java/org/unicode/text/UCD/ToolUnicodePropertySource.java
- unicodetools/src/main/java/org/unicode/text/tools/RecommendedSetGenerator.java
- unicodetools/src/main/java/org/unicode/text/tools/RegexBuilder.java
- unicodetools/src/main/java/org/unicode/text/tools/ShowCharacterFrequency.java
- unicodetools/src/main/java/org/unicode/text/tools/XIDModifications.java
- unicodetools/src/main/java/org/unicode/text/utility/Utility.java
- unicodetools/src/main/java/org/unicode/tools/ExtendedPictographic.java
- unicodetools/src/main/java/org/unicode/tools/Segmenter.java
- unicodetools/src/main/java/org/unicode/tools/UpdateJspFiles.java
some wanted 4 spaces/tab, some 8
> untabify some files

- .flake8
- .github/workflows/pythonpackage.yml
- created .flake8 config file which stores repo-wide options for flake8 Python linter
- tidied up pythonpackage.yml workflow definition file (update to run in Python3.8, other cleanup)
> Update Python workflow & related items

- UnicodeJsps/src/main/java/org/unicode/jsp/CachedProps.java
- at least until #101 is done
For #140
> Turn off IS_BETA

- UnicodeJsps/src/main/webapp/bidic.jsp
- CVERSION was bumped in 161a4917499f22253dd34ec7336f47de69fe950e (#135)
- Just need to update the jsp text
- Reformatted HTML to make variable parts clearer and easier to update.
Note: Bidi-J is on a fixed version and so was not changed.
Fixes #129
> update bidi util to Unicode 14/UBA 14

- .github/workflows/build-jsp.yml
- docs/build.md
> Update Unicode version to 15.0.0 in CI build scripts

- .github/workflows/push-jsp-on-tag.yml
> Push to GCR build broken

- UnicodeJsps/.settings/org.eclipse.core.resources.prefs
- UnicodeJsps/pom.xml
- UnicodeJsps/src/main/java/org/unicode/jsp/UBAVersion.java
- UnicodeJsps/src/main/webapp/bidic.jsp
- UnicodeJsps/src/test/java/org/unicode/jsp/TestUBAVersion.java
https://github.com/unicode-org/unicodetools/issues/129 (but was missed when that was closed)
> jsp: fix C bidi pulldown

- unicodetools/data/ucd/dev/CaseFolding.txt
- unicodetools/data/ucd/dev/HangulSyllableType.txt
- unicodetools/data/ucd/dev/NamesList.txt
- unicodetools/data/ucd/dev/PropertyAliases.txt
- unicodetools/data/ucd/dev/PropertyValueAliases.txt
- unicodetools/data/ucd/dev/ScriptExtensions.txt
- unicodetools/data/ucd/dev/SpecialCasing.txt
Markus,
Updated in the alpha directory:
https://www.unicode.org/Public/15.0.0/ucd/NamesList-15.0.0d2.txt
This reflects some required edits for 4 Kazakh digraphs, based on
Michel's disposition of comments for the CDAM.
> UCD 15.0 updates

- UnicodeJsps/src/main/java/org/unicode/jsp/BiMultimap.java
- UnicodeJsps/src/main/java/org/unicode/jsp/Common.java
- UnicodeJsps/src/main/java/org/unicode/jsp/Globe.java
- UnicodeJsps/src/main/java/org/unicode/jsp/SequenceData.java
- UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeProperty.java
- UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeUtilities.java
- UnicodeJsps/src/main/java/org/unicode/jsp/XPropertyFactory.java
- UnicodeJspsTest/src/org/unicode/jsptest/TestBasicProperties.java
- UnicodeJspsTest/src/org/unicode/jsptest/TestIcuProperties.java
- UnicodeJspsTest/src/org/unicode/jsptest/TestScriptTester.java
> [formatting-only] De-tabify .java files round 2

- pom.xml
> Move from Java source level 8 to source level 11

- docs/uca/index.md
including recommended command-line options
> update UCA.Main instructions

- UnicodeJsps/pom.xml
- pom.xml
- unicodetools/src/main/java/org/unicode/tools/emoji/EmojiImageData.java
> deps: bump cldr to v41, drop xerces

- docs/build.md
- unicodetools/src/main/java/org/unicode/text/UCD/ToolUnicodePropertySource.java
- unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
Fixes issue #220
Fixes issue #221
Fixes issue #222
> fix invariants of lb=SA and of GCB=SpacingMark exceptions

- UnicodeJsps/src/test/java/org/unicode/jsptest/TestIdna.java
- docs/idna.md
- unicodetools/data/idna/dev/IdnaMappingTable.txt
- unicodetools/data/idna/dev/IdnaTestV2.txt
- unicodetools/data/idna/dev/ReadMe.txt
- unicodetools/src/main/java/org/unicode/idna/GenerateIdnaTest.java
... with minor adjustments and cleanups of tools & docs
> Unicode 15 first IDNA data generation

- unicodetools/data/ucd/dev/BidiBrackets.txt
- unicodetools/data/ucd/dev/BidiMirroring.txt
- unicodetools/data/ucd/dev/CJKRadicals.txt
- unicodetools/data/ucd/dev/CompositionExclusions.txt
- unicodetools/data/ucd/dev/EmojiSources.txt
- unicodetools/data/ucd/dev/Jamo.txt
- unicodetools/data/ucd/dev/NamesList.html
- unicodetools/data/ucd/dev/NamesList.txt
- unicodetools/data/ucd/dev/NormalizationCorrections.txt
- unicodetools/data/ucd/dev/NushuSources.txt
- unicodetools/data/ucd/dev/TangutSources.txt
NamesList.txt with changes from UTC 171, and header updates (versions & links) for several files that have no substantive changes. No further changes after UCD.Main data generation.
> Unicode 15 data files 20220504

- unicodetools/src/main/java/org/unicode/tools/emoji/CandidateData.java
> Escape GREATER-THAN SIGN

- unicodetools/data/ucd/dev/LineBreak.txt
- unicodetools/data/ucd/dev/extracted/DerivedLineBreak.txt
- unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
This fixes the one current TestUnicodeInvariants failure.
> lb=EB for new Emoji_Modifier_Base

- docs/build.md
> TestUnicodeInvariants is now run in CI

- .github/workflows/cli-build-instructions.yml
> Add GenerateUnihanCollators and CheckProperties to CI

- unicodetools/data/emoji/dev/emoji-data.txt
- unicodetools/data/emoji/dev/emoji-variation-sequences.txt
- unicodetools/data/ucd/dev/emoji/emoji-data.txt
- unicodetools/data/ucd/dev/emoji/emoji-variation-sequences.txt
- unicodetools/src/main/java/org/unicode/text/utility/Utility.java
- unicodetools/src/main/java/org/unicode/tools/emoji/Emoji.java
- unicodetools/src/main/java/org/unicode/tools/emoji/GenerateEmojiData.java
Automatically generate the KenW-provided version string for emoji files in the UCD.
> Fix version text of UCD emoji files

- .github/workflows/cli-build-instructions.yml
> Add the `ICU` arg to CI test for UCA to also build files for CLDR/ICU

- unicodetools/data/ucd/dev/EastAsianWidth.txt
- unicodetools/data/ucd/dev/extracted/DerivedEastAsianWidth.txt
> remove ea=W from rejected emoji U+1FABE BLACK BIRD

- unicodetools/src/main/java/org/unicode/text/tools/RecommendedSetGenerator.java
Slightly less work copy-pasting into ICU files.
> for ICU: indent ID inclusion/recommended data

- unicodetools/data/ucd/dev/IndicPositionalCategory.txt
- unicodetools/data/ucd/dev/IndicSyllabicCategory.txt
Fixes from @roozbehp for UTC AIs 171-A105 and 171-A106.
> indic props fixes for Kayah Li

- docs/build.md
Followup to #254 to add docs.
Feel free to update branch with changes.
> Instructions about source formatter

- unicodetools/data/emoji/dev/emoji-test.txt
- unicodetools/src/main/java/org/unicode/tools/emoji/EmojiData.java
Fixes [171-A119](https://www.unicode.org/cgi-bin/GetL2Ref.pl?171-A119)
> Fix minimally-qualified sequences

- unicodetools/data/ucd/dev/Index.txt
From @Ken-Whistler and Joe Becker.
First tranche: The usual small set of additions of entries for new blocks.
Second: the rest of the recommendations from Joe, with some adjustments
> Unicode 15 character index additions

- unicodetools/data/ucd/dev/NamesList.html
From Ken: There were no content changes and no comments on NamesList.html for 15.0. I just did the cleanup for release and staged up. (This just changed the draft status and date on the document.)
> clean up NamesList.html

- unicodetools/data/ucd/dev/NamesList.txt
From Ken: This rolls in all the open actions I knew about for beta feedback, etc. It is mostly a bunch of small, local annotation fixes. I synched the notice for the Kazakh letters 0675..0678
> Names List updated to final for 15.0

- unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
- removed exceptions from test
- updated description to indicate that the test allows for possible future exceptions (but that no exceptions are currently defined).
closes #289
> Update Invariant Test and description for InSC=Bindu Alphabetic=Yes

- unicodetools/data/uca/dev/CollationTest.html
- removed "changed" styles and "removed" note
- updated UTS 10 links to tr10-47 for UCA 15 publication
> clean up CollationTest.html for UCA 15

- unicodetools/data/ucd/dev/NamesList.txt
- unicodetools/data/ucd/dev/emoji/ReadMe.txt
From Ken:
- NamesList-15.0.0d7.txt -- cleanup of intermediate change notes at the top of the file only, no other content change.
- emoji/ReadMe.txt -- I removed the "draft" note and added a date/time line.
> UCD Updates: NamesList and emoji ReadMe.txt

- unicodetools/data/emoji/dev/ReadMe.txt
- unicodetools/data/idna/dev/ReadMe.txt
- unicodetools/data/security/dev/ReadMe.txt
- unicodetools/data/ucd/dev/ReadMe.txt
For each file, I am using the same "final" wording as in Unicode 14.
> Unicode 15 final readmes

- unicodetools/data/emoji/dev/emoji-zwj-sequences.txt
- unicodetools/data/ucd/dev/Index.txt
sync the final Unicode 15 UCD, UCA, emoji, idna, security files into this repo
> Unicode 15 final data files

- docs/build.md
- docs/data-workflow.md
Based on discussions in the Properties & Algorithms group on 2021-nov-08, 2022-mar-15, 2022-apr-25.
For issue #172
> Unicode 15.1+ data workflow

- unicodetools/src/main/java/org/unicode/tools/emoji/ChartUtilities.java
- unicodetools/src/main/resources/org/unicode/tools/emoji/emoji-list.css
These are the tool changes made to generate the current (blue) charts.
> Changes for blue E15.0 charts

- unicodetools/data/emoji/dev/ReadMe.txt
- unicodetools/data/idna/dev/ReadMe.txt
- unicodetools/data/security/dev/ReadMe.txt
- unicodetools/data/uca/dev/ReadMe.txt
- unicodetools/data/ucd/dev/ReadMe.txt
- unicodetools/data/ucd/dev/emoji/ReadMe.txt
including a few that we do not plan to publish as part of the initial alpha review
New folder structure in Public for the alpha & beta:
https://github.com/unicode-org/unicodetools/blob/main/docs/data-workflow.md
These are fairly straight updates. Elsewhere we have an ongoing discussion about the different styles of readme files: https://github.com/unicode-org/properties/issues/8
This is also missing a couple of files. I will add those in another PR: https://github.com/unicode-org/unicodetools/issues/327
> update several readmes for 15.1 alpha/beta

- unicodetools/data/ucd/dev/version-ReadMe.txt
- unicodetools/data/ucd/dev/zipped-ReadMe.txt
- add https://www.unicode.org/Public/15.0.0/ReadMe.txt as .../data/ucd/dev/version-ReadMe.txt
- add https://www.unicode.org/Public/zipped/15.0.0/ReadMe.txt as .../data/ucd/dev/zipped-ReadMe.txt
... as discussed in issue #327.
Then update these for Unicode 15.1.
> add UCD & zipped readme files

- unicodetools/data/ucd/dev/ScriptExtensions.txt
* Add Sinh and Mlym to scx of U+1CF2
* Add Shrd to scx of U+A830..U+A835 and U+A838
* Sort scripts, first by count, and then alphabetically
This brings ScriptsExtensions.txt in sync with commit 67fa2d1bcb4dca1e8f296f1ffca59a3011718179 in https://github.com/roozbehp/unicode-data
> Update ScriptExtensions.txt for Unicode 15.1

- unicodetools/data/ucd/dev/USourceData.txt
From @Tsengtsz: One changed needed in USourceData.txt had been overlooked and has now been made. (= addendum for PR #396)
> USourceData.txt one more change

- docs/build.md
- docs/inputdata.md
- docs/security.md
- docs/uca/index.md
More docs changes. For issue #172 I looked through the docs and made changes as necessary.
I did not read every word on every page... after merging this PR, I intend to check off the items in #172, close that issue, and when we need to make more changes, we do.
> more updates for 15.1 data workflow

- pub/copy-alpha-to-draft.sh
Set file & dir permissions.
Add a command to zip the files, to remove a manual step.
> publish alpha: everyone can read files, search dirs; zip files

- UnicodeJsps/Dockerfile
- rearrange the docker file so that caching works better
- remove -q (quiet) from the apk command
Fixes #343
> chore(deps): Unicode 15 update of the UnicodeJsps bidi-c demo

- unicodetools/src/main/java/org/unicode/tools/emoji/GenerateEmojiData.java
- unicodetools/src/main/resources/org/unicode/text/UCD/StandardizedVariants-Template.html
Fix code that generates UCD/StandardizedVariants.txt and emoji/emoji-sequences.txt.
> Replace references to UTR #51 with UTS #51

- unicodetools/src/main/java/org/unicode/text/UCD/GenerateCaseFolding.java
- unicodetools/src/main/java/org/unicode/text/UCD/UData.java
Add a consistency check.
#426 for follow-up.
This one is going to be easier to review without the spaces: https://github.com/unicode-org/unicodetools/pull/427/files?w=1.
> Fix case folding using getCase

- unicodetools/data/ucd/dev/NamesList.txt
Change log from the header in the file:
- Unicode 15.1.0 names list, sixth delta.
- Repertoire synched with UnicodeData-15.1.0d2.txt.
- Added annotations for Lisu.
- Added xrefs for 2268 and 2269.
- Added annotation for 06DE.
- Added header for CJK Extension I.
- Extensive set of annotations per EDC review of public feedback.
> NamesList from Ken may08

- unicodetools/src/main/java/org/unicode/text/UCD/ToolUnicodePropertySource.java
- unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
This does not address #385 nor #386, but should hopefully provide a straightforward template for those.
> Add missing invariant tests for a handful of stability policies

- unicodetools/data/ucd/dev/TangutSources.txt
from @michelsu
with a small white space fix in the header comment
> TangutSources apr26

- unicodetools/data/ucd/dev/Index.txt
From Ken: add entries for CJK Extension I, for consistency.
> Index.txt 15.1 may22 with CJK ext I

- unicodetools/data/ucdxml/15.0.0/ucdxml.readme.txt
- unicodetools/data/ucdxml/dev/ucdxml.readme.txt
Two commits:
- Make a copy of the 15.0 data. I forgot to do that last year.
- 15.1 data from @liancu-uni
I ran CheckXmlProperties and it has a lot of complaints, but at a glance they all look like the kinds of things noted in issues #125 & #325.
> UCDXML 15.1 beta from may22

- unicodetools/data/emoji/dev/emoji-zwj-sequences.txt
- unicodetools/src/main/java/org/unicode/tools/emoji/CountEmoji.java
Fix https://www.unicode.org/review/pri480/feedback.html#ID20230524133634
> PRI #480 emoji feedback

- docs/emoji/index.md
- unicodetools/src/main/java/org/unicode/tools/emoji/Emoji.java
- unicodetools/src/main/java/org/unicode/tools/emoji/EmojiAnnotations.java
- unicodetools/src/main/java/org/unicode/tools/emoji/GenerateEmoji.java
For the result of these changes, see https://github.com/unicode-org/emoji/pull/30.
This completes
[[176-A143](https://www.unicode.org/cgi-bin/GetL2Ref.pl/?176-A143)] Action Item for Ned Holbrook, ESC: Prepare final candidate data files for the data directory of UTS51, and a complete set of emoji final charts for Emoji 15.1.
> Emoji 15.1 final charts

- docs/data-workflow.md
- pub/copy-alpha-to-draft.sh
- pub/copy-beta-to-draft.sh
- pub/copy-final.sh
- unicodetools/data/emoji/dev/ReadMe.txt
- unicodetools/data/idna/dev/ReadMe.txt
- unicodetools/data/idna/idna2008derived/ReadMe.txt
- unicodetools/data/security/dev/ReadMe.txt
- unicodetools/data/uca/dev/ReadMe.txt
- unicodetools/data/ucd/dev/ReadMe.txt
- unicodetools/data/ucd/dev/emoji/ReadMe.txt
- unicodetools/data/ucd/dev/version-ReadMe.txt
- unicodetools/data/ucd/dev/zipped-ReadMe.txt
New publication script for assembling the data files (as far as they are kept in this repo) for a Unicode release.
The various ReadMe.txt files are now templatized, and the publication scripts fill in some variables. I chose `find` and `sed` because it was easy.
> script to publish final files; templatize readmes

- docs/unicodejsps/index.md
> fix: jsp: fix docs on running jetty from the command line

- .gitignore
- UnicodeJsps/Dockerfile
- docs/unicodejsps/gcp-run.md
- docs/unicodejsps/index.md
- some docs on the new GCP run environment
- update the Dockerfile to be less vulnerable
For #523
-----
This is somewhat of a work in progress document, but I think it's probably worth adding becasue the existing unicodejsps/index.md is slightly out of date.
> chore(jsp): wip docs and updated dockerfile

- pub/copy-beta-to-draft.sh
- pub/copy-final.sh
- unicodetools/data/uca/dev/CollationTest.html
like the ReadMe.txt files, replacing routine manual updates
> templatize CollationTest.html

- unicodetools/data/ucd/dev/ArabicShaping.txt
Fixes https://github.com/unicode-org/edcom/issues/80
> Code points are no longer limited to 4 digits

- unicodetools/src/main/java/org/unicode/text/UCD/UCD_Names.java
- unicodetools/src/main/java/org/unicode/text/UCD/UCD_Types.java
Following up on #443; these codes were added on 2023-09-12: https://unicode.org/iso15924/codechanges.html.
> Script codes from the future

- UnicodeJsps/jetty.d/ROOT/robots.txt
> feat(jsp): robots.txt for JSP utilities

- docs/pipeline.md
Included @markusicu’s translation from https://github.com/unicode-org/unicodetools/pull/375#issuecomment-1758572597, all other scripts are Windows in-source.
> Check in my UCD checklist

- unicodetools/data/ucd/dev/ArabicShaping.txt
Contains best of both worlds information, including a typo fix in the header.
> Merge ArabicShaping.txt with Ken Whistler's latest draft

- unicodetools/data/ucd/dev/ScriptExtensions.txt
UTC-177-C31 Consensus: Add Tulu-Tigalari entries to ScriptExtensions.txt file as documented in L2/23-217 for Unicode version 16.0.
UTC-177-A73 Action Item for Roozbeh Pournader, SAH: Add the value Tutg (Tulu-Tigalari) in ScriptExtensions.txt for the characters listed in L2/23-217 for Unicode version 16.0. (Ref. Section 7 of L2/23-238)
> Add Tulu-Tigalari to ScriptExtensions.txt for various characters

- unicodetools/data/idna/dev/IdnaMappingTable.txt
- unicodetools/data/idna/dev/IdnaTestV2.txt
Early generation of IDNA files from current Unicode 16.0 data.
@michelsu FYI
> IDNA 16.0 first files

- unicodetools/data/ucd/dev/NamesList.txt
d7 update from Ken, up from d3 here
> Unicode 16 NamesList.txt d7

- pom.xml
> Update to CLDR 44.1

- unicodetools/src/main/java/org/unicode/props/UnicodeProperty.java
- unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
Also make most of the Unihan invariants live (but someone who knows what they are doing should look at the performance of that kHanyuPinyin UnicodeSet).
> Fix the handling of multivalued Unihan properties

- unicodetools/src/main/resources/org/unicode/tools/emoji/docRegistry.txt
I followed the instructions of docs/emoji/index.md and filled in the remaining lines through the end of 2023.
> Update docRegistry.txt to end of 2023

- unicodetools/data/ucd/dev/ArabicShaping.txt
This is considered editorial. The text comes from Ken Whistler.
> Update ArabicShaping.txt to better document it being contributory

- unicodetools/data/ucd/dev/NamesList.txt
- unicodetools/data/ucd/dev/Unikemet.txt
```
[TXT]   Unikemet-16.0.0d10.txt  2024-02-01 16:03        1.4M
[TXT]   NamesList-16.0.0d12.txt 2024-02-01 16:00        1.9M
```
> Fresh Kenfiles

- pub/copy-alpha-to-draft.sh
- pub/copy-beta-to-draft.sh
- pub/copy-final.sh
and publish IDNA files already in the alpha
> publish 16.0 files with copy=2024

- unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
UTC-151-A143 **Action Item for** <del>Mark Davis, Laurențiu Iancu: </del><ins>Robin Leroy, Josh Hadley, PAG: </ins>Add invariant tests for new property and property values from PRI-344.
> Some more Equivalent_Unified_Ideograph invariants

- unicodetools/data/ucd/dev/NamesList.txt
@Ken-Whistler wrote:
> Another alpha review feedback item: I updated the subhead for 16100 in Gurung Khema.
> NamesList-16.0.0d13.txt

- unicodetools/data/ucd/dev/PropList.txt
- unicodetools/data/ucd/dev/auxiliary/WordBreakProperty.txt
See https://github.com/unicode-org/properties/issues/250.
> Make U+18CFF ideographic.

- unicodetools/src/main/java/org/unicode/props/IndexUnicodeProperties.java
- unicodetools/src/main/java/org/unicode/props/PropertyParsingInfo.java
- unicodetools/src/main/java/org/unicode/props/UnicodeProperty.java
Some progress towards #650.
| | Before | After |
|-|---|--|
| A | ![image](https://github.com/unicode-org/unicodetools/assets/2284290/3a7ab597-8510-4cb6-8e56-e343fc0d0972) | ![image](https://github.com/unicode-org/unicodetools/assets/2284290/17bf89dd-60a8-4214-8669-573844e555e7) |
| 㐀 | ![image](https://github.com/unicode-org/unicodetools/assets/2284290/89763bb8-7b8c-4276-8c28-37b249ec96aa) | ![image](https://github.com/unicode-org/unicodetools/assets/2284290/231ed748-e0a0-4339-889d-9cfe1cdc20df) |
> Old blocks and unborn properties

- unicodetools/src/main/java/org/unicode/props/IndexUnicodeProperties.java
- unicodetools/src/main/java/org/unicode/props/PropertyParsingInfo.java
- unicodetools/src/main/java/org/unicode/props/PropertyStatus.java
- unicodetools/src/main/java/org/unicode/tools/ListProps.java
- unicodetools/src/main/resources/org/unicode/props/ExtraPropertyValueAliases.txt
- unicodetools/src/test/java/org/unicode/propstest/CheckProperties.java
- unicodetools/src/test/java/org/unicode/propstest/CheckPropertyStability.java
- unicodetools/src/test/java/org/unicode/propstest/ListAssignedWithDefaultValues.java
> Fix U9.0:Identifier_Type defaults

- UnicodeJsps/src/main/java/org/unicode/jsp/UcdLoader.java
Fix #728. Pushed this to prod (staging did not have the issue at all), it seems to have fixed things:
> Ensure we have 16.0 before serving

- docs/pipeline.md
> Some tweaks to the Pipeline docs

- UnicodeJsps/src/main/java/org/unicode/jsp/UnicodeUtilities.java
- UnicodeJsps/src/main/webapp/index.css
- docs/unicodejsps/index.md
Sadly not Cs, even though it has really pretty glyphs for those, since that is not interchangeable, so that I cannot get them to show up.
Fix #725.
> Use the Last Resort font for Co, Cn, and most Cc

- unicodetools/data/ucd/dev/ScriptExtensions.txt
[178-C28] Consensus: Revise entries in the ScriptExtensions.txt file to add values as documented in L2/23-272, for Unicode Version 16.0: Mong to U+3001, Mong Phag to U+3002, and Mong Tibt to U+3008, U+3009, U+300A, U+300B. [Ref. Section 4 of L2/24-013R]
[178-A77] Action Item for Roozbeh Pournader, PAG: Add Mong to scx of U+3001, Mong Phag to U+3002, and Mong Tibt to U+3008, U+3009, U+300A, U+300B, for Unicode Version 16.0. [Ref. Section 4 of L2/24-013R]
(Part of this was already done in a0f44094c48533b1409d7fa70c6258d296c75f7b.)
> Add Mong Tibt to scx of 3008..300B

- unicodetools/data/ucd/dev/NamesList.txt
> Updated with some new cross-references from today's SAH meeting[.]
> NamesList-16.0.0d16.txt

- unicodetools/src/main/java/org/unicode/props/IndexUnicodeProperties.java
- unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
Fix versioned property (which was broken because isTrivial was broken) and getSet when using incremental properties (which we do on the JSPs).
> String property fixes

- docs/pipeline.md
- py/pipeline-workflow/check-l2-document.py
- py/pipeline-workflow/check-utc-decision.py
See https://github.com/unicode-org/unicodetools/pull/637#issuecomment-1865382021.
Since we now write a PAG review in the SAH issue based on these PRs, it is really useful to have a link, so adding a reminder to put that link in the description.
> Paper trail improvements

- docs/emoji/ordering.md
- unicodetools/data/emoji/dev/emoji-sequences.txt
- unicodetools/data/emoji/dev/emoji-test.txt
- unicodetools/data/emoji/dev/emoji-zwj-sequences.txt
- unicodetools/data/emoji/dev/internal/emoji-internal.txt
- unicodetools/data/emoji/dev/internal/emoji-sequences-nonrgi.txt
- unicodetools/data/emoji/dev/internal/emoji-zwj-sequences-nonrgi.txt
- unicodetools/data/ucd/dev/emoji/emoji-data.txt
- unicodetools/data/ucd/dev/emoji/emoji-variation-sequences.txt
- unicodetools/src/main/java/org/unicode/tools/emoji/GenerateCldrData.java
No substantive data changes, only updates to common header verbiage. Also fix GenerateCldrData.java for @macchiati.
> Emoji 16.0 beta data

- unicodetools/data/ucd/dev/TangutSources.txt
> Correct the section number for Tangut in TangutSources.txt

- unicodetools/data/ucdxml/dev/ucdxml.readme.txt
> UCDXML 16 may16

- unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
Relevant to unicode-org/properties#286.
> Another $unihanScope characterization

- unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
Fixes https://github.com/unicode-org/unicodetools/issues/848
> HST invariants

- unicodetools/data/ucd/dev/ScriptExtensions.txt
[UTC-180-C42] Consensus: Add Runr to the Script_Extensions of U+16EB RUNIC SINGLE PUNCTUATION, U+16EC RUNIC MULTIPLE PUNCTUATION, U+16ED RUNIC CROSS PUNCTUATION for Unicode Version 16.0 [Ref. Section 24 of document L2/24-166]
[UTC-180-A106] Action Item for Roozbeh Pournader, PAG: Add Runr to the Script_Extensions of U+16EB RUNIC SINGLE PUNCTUATION, U+16EC RUNIC MULTIPLE PUNCTUATION, U+16ED RUNIC CROSS PUNCTUATION for Unicode Version 16.0 [Ref. Section 24 of document L2/24-166]
> Add Runic to scx of U+16EB..U+16ED

- unicodetools/data/ucd/dev/Index.txt
From Ken:
I've done the BRS items related to updating the character names index.
This just adds about a dozen new entries for 16.0, plus rolling in a fix for one item noted in feedback earlier.
> UCD 16.0: Update for Index.txt

- unicodetools/data/uca/dev/CollationTest.html
New text from @annebright & team
> CollationTest.html copyright 2024

- unicodetools/src/main/java/org/unicode/text/UCA/MakeNamesChart.java
- unicodetools/src/main/java/org/unicode/text/UCA/WriteCharts.java
- unicodetools/src/main/resources/org/unicode/text/UCA/HTML-Part2.txt
- unicodetools/src/main/resources/org/unicode/text/UCA/case_help.html
- unicodetools/src/main/resources/org/unicode/text/UCA/charts.css
- unicodetools/src/main/resources/org/unicode/text/UCA/help.html
- unicodetools/src/main/resources/org/unicode/text/UCA/name_help.html
- unicodetools/src/main/resources/org/unicode/text/UCA/nameslist.css
- unicodetools/src/main/resources/org/unicode/text/UCA/nameslist_help.html
- unicodetools/src/main/resources/org/unicode/text/UCA/norm_help.html
- unicodetools/src/main/resources/org/unicode/text/UCA/script_help.html
New text from @annebright & team
This text will appear in the right / bottom-right frame on each of the aux charts pages.
> add Website Persistent Footer to aux charts

- unicodetools/data/ucd/dev/NamesList.html
Changes from Ken after iterating with Asmus & Michel.
> Unicode 16 NamesList.html 20240821

- unicodetools/src/main/java/org/unicode/text/UCA/WriteCharts.java
Fixes
- https://github.com/unicode-org/unicodetools/issues/922
by changing the script chart generator so that it shows each character on exactly one chart, which is the one with its explicit script (which could be from scx if there is exactly one explicit value).
Avoids showing characters on multiple charts because they or their decomposition mappings have multiple Script_Extensions. The per-script charts are now cleaner than before, and there are more per-General_Category charts for characters that don't have one single explicit script.
> script charts: each character on exactly one

- unicodetools/data/ucd/dev/ArabicShaping.txt
- unicodetools/data/ucd/dev/BidiBrackets.txt
- unicodetools/data/ucd/dev/BidiMirroring.txt
- unicodetools/data/ucd/dev/Blocks.txt
- unicodetools/data/ucd/dev/CJKRadicals.txt
- unicodetools/data/ucd/dev/CompositionExclusions.txt
- unicodetools/data/ucd/dev/DoNotEmit.txt
- unicodetools/data/ucd/dev/EmojiSources.txt
- unicodetools/data/ucd/dev/EquivalentUnifiedIdeograph.txt
- unicodetools/data/ucd/dev/HangulSyllableType.txt
- unicodetools/data/ucd/dev/Jamo.txt
- unicodetools/data/ucd/dev/NameAliases.txt
- unicodetools/data/ucd/dev/NamedSequences.txt
- unicodetools/data/ucd/dev/NamedSequencesProv.txt
- unicodetools/data/ucd/dev/NormalizationCorrections.txt
- unicodetools/data/ucd/dev/NushuSources.txt
- unicodetools/data/ucd/dev/PropertyAliases.txt
- unicodetools/data/ucd/dev/SpecialCasing.txt
- unicodetools/data/ucd/dev/TangutSources.txt
- unicodetools/data/ucd/dev/Unikemet.txt
- unicodetools/data/ucd/dev/auxiliary/SentenceBreakTest.txt
- unicodetools/data/ucd/dev/auxiliary/WordBreakTest.txt
- unicodetools/data/ucd/dev/extracted/DerivedBinaryProperties.txt
and adjust in-file dates for files that have changed after 16
> in-file versions 16->17

- unicodetools/data/ucd/dev/ScriptExtensions.txt
[181-C42] Consensus: Revise entries in ScriptExtensions.txt file to add Tfng to U+0306, U+0308, and U+0323, for Unicode Version 17.0. [Ref. Section 4.2 of document L2/24-228]
[181-A106] Action Item for Roozbeh Pournader, PAG: Revise entries in ScriptExtensions.txt file to add Tfng to U+0306, U+0308, and U+0323, for Unicode Version 17.0 [Ref. Section 4.2 of document L2/24-228]
> Add Tfng to scx of U+0306, U+0308, and U+0323

- unicodetools/data/ucd/dev/TangutSources.txt
fixes https://github.com/unicode-org/unicodetools/issues/991
reported by @lianghai
> remove TangutSources conflict markers

- unicodetools/data/ucd/dev/EmojiSources.txt
See discussion in PAG issue 325
> EmojiSources: no changes anticipated

- .github/workflows/build-jsp.yml
Fixes: #1010
yeah, turns out it's needed inside the war because of how it's built.
- also upgrade an artifact action
> jsp: The Last Resort font should be downloaded by build-jsp.yml

- docs/pipeline.md
We now have comparison tests, summaries in the reports, and some dashboard status wrangling as part of this exercise.
> Update the pipeline documentation to cover changes in process

- unicodetools/data/ucd/dev/NamesList.txt
I have rolled in some annotation fixes after EDC review of some alpha feedback.
[…]
This represents me trying to stay on top of various action items due before beta.
> NamesList-17.0.0d13.txt

- unicodetools/src/main/java/org/unicode/text/utility/Utility.java
- unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
> Do not fall back when looking for 4.1 data or later

- unicodetools/data/idna/dev/IdnaMappingTable.txt
- unicodetools/data/idna/dev/IdnaTestV2.txt
expected adjustments for recent repertoire changes
> Unicode 17 beta IDNA

- .github/workflows/codeql.yml
> Update codeql actions to v3

- UnicodeJsps/src/main/java/org/unicode/jsp/XPropertyFactory.java
- UnicodeJsps/src/test/java/org/unicode/jsptest/TestJsp.java
- unicodetools/src/main/java/org/unicode/props/PropertyParsingInfo.java
- unicodetools/src/main/java/org/unicode/props/UcdProperty.java
- unicodetools/src/main/java/org/unicode/props/UcdPropertyValues.java
- unicodetools/src/main/java/org/unicode/text/utility/Utility.java
- unicodetools/src/main/resources/org/unicode/props/ExtraPropertyAliases.txt
- unicodetools/src/main/resources/org/unicode/props/ExtraPropertyValueAliases.txt
- unicodetools/src/main/resources/org/unicode/props/IndexUnicodeProperties.txt
- unicodetools/src/main/resources/org/unicode/text/UCD/UnicodeInvariantTest.txt
- unicodetools/src/test/java/org/unicode/propstest/TestInvariants.java
- unicodetools/src/test/java/org/unicode/text/UCD/TestCodeInvariants.java
Instead of hacking them without history into the JSPs.
> Add non-UCD properties to IUP

- docs/ucdxml.md
... and add Linux versions of Maven command lines
> Unicode 17 beta: regen UCDXML

- README.md
- UnicodeJsps/README.md
- UnicodeJsps/src/main/webapp/footer.jsp
- UnicodeJsps/src/main/webapp/index.css
- docs/help/index.md
- docs/unicodejsps/index.md
- copyright and terms of use on util.unicode.org footer and help page
- link to source repo
Fixes: #1015
> chore(jsp): © / TOU on footer, also mention source

- unicodetools/data/ucd/dev/ScriptExtensions.txt
[UTC-184-C24] Consensus: Revise entries in the ScriptExtensions.txt file to add Newa, Shrd, Telu, Nand or Tirh for 17 characters as described in L2/25-154, for Unicode Version 17.0. [Ref. 3.5 in L2/25-187]
[UTC-184-A50] Action Item for Roozbeh Pournader, PAG: Revise entries in ScriptExtensions.txt file to add Newa, Shrd, Telu, Nand or Tirh as described in L2/25-154, for Unicode Version 17.0. [Ref. 3.5 in L2/25-187]
> Extend ScriptExtensions for various Vedic characters

- unicodetools/data/ucd/dev/BidiBrackets.txt
- unicodetools/data/ucd/dev/BidiMirroring.txt
- unicodetools/data/ucd/dev/Blocks.txt
- unicodetools/data/ucd/dev/CompositionExclusions.txt
- unicodetools/data/ucd/dev/EmojiSources.txt
- unicodetools/data/ucd/dev/EquivalentUnifiedIdeograph.txt
- unicodetools/data/ucd/dev/NamedSequencesProv.txt
- unicodetools/data/ucd/dev/NormalizationCorrections.txt
I guess that these are all hand-edited.
> Unicode 17 data files should say 2025

- unicodetools/data/ucdxml/dev/ucdxml.readme.txt
straightforward generation after recent data changes
> UCDXML 17 2025-aug-04

- unicodetools/data/ucd/dev/NamesList.html
from Ken, just updating version 16 to 17
> NamesList-17.0.0d2.html

- pub/copy-alpha-to-draft.sh
- pub/copy-beta-to-draft.sh
- pub/copy-final.sh
- pub/copy-ucd-to-draft.sh
- pub final: catch up with changes for beta, except still exclude links
- pub non-final: rename DRAFT to DEST so that these files are easily comparable with pub final
> pub final uni17 & align pub scripts

- docs/build.md
Updates to the CLDR docs on Maven will come in a subsequent PR in CLDR
> Update doc for setup of Github tokens to use Github Maven artifacts
